from __future__ import annotations

T = dict[str, str]


def t(en: str, ar: str, fr: str, es: str) -> T:
    return {"en": en, "ar": ar, "fr": fr, "es": es}


COLLECTIONS = [
    {
        "slug": "creator-lab",
        "sort": 1,
        "image": "/images/collections/creator-lab.png",
        "name": t("Creator Lab", "مختبر الصانع", "Creator Lab", "Creator Lab"),
        "sub": t(
            "Systems for people who publish.",
            "أنظمة للي ينشرون.",
            "Des systèmes pour ceux qui publient.",
            "Sistemas para quienes publican.",
        ),
    },
    {
        "slug": "ai-command",
        "sort": 2,
        "image": "/images/collections/ai-command.png",
        "name": t("AI Command", "قيادة الذكاء", "AI Command", "AI Command"),
        "sub": t(
            "Operate AI like staff.",
            "شغّل الذكاء كموظف.",
            "Faites travailler l’IA comme une équipe.",
            "Opera la IA como si fuera tu equipo.",
        ),
    },
    {
        "slug": "wealth-os",
        "sort": 3,
        "image": "/images/collections/wealth.png",
        "name": t("Wealth", "الثروة", "Riqueza", "Riqueza"),
        "sub": t(
            "Money and time as an operator.",
            "الفلوس والوقت بصيغة مشغّل.",
            "L’argent et le temps, en opérateur.",
            "Dinero y tiempo, como un operador.",
        ),
    },
    {
        "slug": "glow-ritual",
        "sort": 4,
        "image": "/images/collections/glow.png",
        "name": t("Glow Ritual", "طقوس التوهج", "Rituel Glow", "Ritual Glow"),
        "sub": t(
            "Private luxury rituals.",
            "طقوس خاصة، شكلها غالي.",
            "Des rituels privés, luxe calme.",
            "Rituales privados, lujo silencioso.",
        ),
    },
    {
        "slug": "the-vault",
        "sort": 5,
        "image": "/images/collections/vault.png",
        "name": t("The Vault", "الخزنة", "La Chambre forte", "La Bóveda"),
        "sub": t(
            "The whole house. One key.",
            "الدار كاملة. مفتاح واحد.",
            "Toute la maison. Une clé.",
            "Toda la casa. Una llave.",
        ),
    },
]


def imgs(slug: str) -> list[str]:
    return [f"/images/products/{slug}/0{i}.png" for i in range(1, 5)]


def faq_block(en_q: str, en_a: str, ar_q: str, ar_a: str, fr_q: str, fr_a: str, es_q: str, es_a: str) -> dict:
    return {
        "en": {"q": en_q, "a": en_a},
        "ar": {"q": ar_q, "a": ar_a},
        "fr": {"q": fr_q, "a": fr_a},
        "es": {"q": es_q, "a": es_a},
    }


COMMON_FAQS = [
    faq_block(
        "How do I receive the system?",
        "After you confirm name and email, we send vault instructions to that inbox.",
        "كيف توصلني الخزنة؟",
        "بعد الاسم والإيميل، توصلك التعليمات على نفس الإيميل.",
        "Comment je reçois le système ?",
        "Après nom et e-mail, les instructions du coffre arrivent dans cette boîte.",
        "¿Cómo recibo el sistema?",
        "Tras nombre y email, enviamos las instrucciones del vault a esa bandeja.",
    ),
    faq_block(
        "Is this a PDF dump?",
        "No. Each SKU is a sequenced operating system with a start-here and a studio serial.",
        "هذا PDF مرمي؟",
        "لا. كل منتج نظام مرتّب، فيه start-here، وعليه رقم استوديو.",
        "C’est un dump de PDF ?",
        "Non. Chaque SKU est un système séquencé, avec un start-here et un numéro de studio.",
        "¿Es un dump de PDFs?",
        "No. Cada SKU es un sistema secuenciado, con start-here y número de estudio.",
    ),
    faq_block(
        "Can I use this for a team?",
        "Personal license is for you. Duo is two people. No redistribution.",
        "أقدر أعطيه للفريق؟",
        "الرخصة الشخصية لك. الثنائية لشخصين. بدون إعادة نشر.",
        "Pour une équipe ?",
        "Licence perso = vous. Duo = deux personnes. Pas de redistribution.",
        "¿Para un equipo?",
        "Licencia personal = tú. Dúo = dos personas. Sin redistribución.",
    ),
    faq_block(
        "Do you ship physical goods?",
        "No. Worldwide digital only.",
        "في شحن؟",
        "لا. رقمي لكل العالم.",
        "Livraison physique ?",
        "Non. 100 % numérique, monde entier.",
        "¿Envío físico?",
        "No. Solo digital, en todo el mundo.",
    ),
    faq_block(
        "Why $19 if it’s premium?",
        "The door is $19. The house is the pair, the cart, the vault.",
        "ليش 19$ وهو فخم؟",
        "الباب 19$. الدار هي الثنائية والخزنة.",
        "Pourquoi 19 $ si c’est premium ?",
        "La porte est à 19 $. La maison, c’est le duo, le panier, le vault.",
        "¿Por qué 19 $ si es premium?",
        "La puerta es 19 $. La casa es el dúo, el carrito, el vault.",
    ),
    faq_block(
        "Refunds?",
        "7 days if the vault files are wrong or won’t open.",
        "استرجاع؟",
        "7 أيام إذا الملفات غلط أو ما تنفتح.",
        "Remboursement ?",
        "7 jours si les fichiers du coffre sont faux ou ne s’ouvrent pas.",
        "¿Reembolso?",
        "7 días si los archivos del vault están mal o no abren.",
    ),
]


PRODUCTS = [
    {
        "sku": "DW-SYS-001",
        "slug": "creator-os",
        "collection": "creator-lab",
        "type": "system",
        "serial": "DW-SYS-001",
        "price_cents": 1900,
        "pair_sku": "hook-vault",
        "pair_price_cents": 3400,
        "upsell_sku": "faceless-studio",
        "upsell_price_cents": 1100,
        "cross_sell": ["hook-vault", "faceless-studio", "caption-machine"],
        "sort": 1,
        "name": t("Creator OS", "نظام الصانع", "Creator OS", "Creator OS"),
        "sub": t(
            "The content operating system for people who are done posting at random.",
            "نظام المحتوى للي تعب ينزل عشوائي.",
            "Le système d’exploitation du contenu, pour ceux qui en ont assez de publier au hasard.",
            "El sistema operativo de contenido para quien ya no publica al azar.",
        ),
        "headline": t(
            "Post like a studio. Not like a mood.",
            "انشر كاستوديو. مو حسب مزاجك.",
            "Publiez comme un studio. Pas comme une humeur.",
            "Publica como un estudio. No como un mood.",
        ),
        "description": t(
            "Hooks, UGC frames, a 30-day filming map, caption OS, weekly review, offer-to-content bridge.",
            "هوكس، إطارات UGC، خارطة تصوير 30 يوم، نظام كابشن، مراجعة أسبوعية.",
            "Hooks, cadres UGC, carte de tournage 30 jours, OS légendes, revue hebdo.",
            "Hooks, marcos UGC, mapa de filmación 30 días, OS de captions, revisión semanal.",
        ),
        "contents": t(
            "Hook OS · UGC script frames · 30-day filming map · Caption OS · Weekly review · Offer-to-content bridge",
            "نظام الهوكس · إطارات سكربت UGC · خارطة 30 يوم · نظام الكابشن · مراجعة أسبوعية · جسر العرض",
            "Hook OS · cadres UGC · carte 30 jours · Caption OS · revue hebdo · pont offre→contenu",
            "Hook OS · marcos UGC · mapa 30 días · Caption OS · revisión semanal · puente oferta→contenido",
        ),
        "images": imgs("creator-os"),
        "faq": COMMON_FAQS,
    },
    {
        "sku": "DW-SYS-002",
        "slug": "faceless-studio",
        "collection": "creator-lab",
        "type": "system",
        "serial": "DW-SYS-002",
        "price_cents": 1900,
        "pair_sku": "creator-os",
        "pair_price_cents": 3400,
        "upsell_sku": "hook-vault",
        "upsell_price_cents": 1100,
        "cross_sell": ["creator-os", "hook-vault", "ad-swipe"],
        "sort": 2,
        "name": t("Faceless Studio", "استوديو بدون وجه", "Faceless Studio", "Faceless Studio"),
        "sub": t(
            "Build a faceless channel without looking cheap.",
            "قناة بدون وجه، بس شكلها استوديو.",
            "Une chaîne faceless qui a encore l’air chère.",
            "Un canal faceless que sigue viéndose caro.",
        ),
        "headline": t(
            "A faceless brand that still looks expensive.",
            "قناة بدون وجه، وشكلها غالي.",
            "Une marque sans visage, encore luxueuse.",
            "Una marca sin rostro, todavía cara.",
        ),
        "description": t(
            "Niche picker, script engine, B-roll shot list, CapCut SOP, posting cadence, monetization map.",
            "اختيار النيتش، محرك السكربت، لائحة لقطات، SOP كاب كت، إيقاع النشر.",
            "Choix de niche, moteur de scripts, liste B-roll, SOP CapCut, cadence.",
            "Selector de nicho, motor de scripts, lista B-roll, SOP CapCut, cadencia.",
        ),
        "contents": t(
            "Niche picker · Script engine · B-roll list · CapCut SOP · Cadence · Monetization map",
            "نيتش · سكربت · B-roll · كاب كت · إيقاع · تسييل",
            "Niche · scripts · B-roll · CapCut · cadence · monétisation",
            "Nicho · scripts · B-roll · CapCut · cadencia · monetización",
        ),
        "images": imgs("faceless-studio"),
        "faq": COMMON_FAQS,
    },
    {
        "sku": "DW-SYS-003",
        "slug": "hook-vault",
        "collection": "creator-lab",
        "type": "system",
        "serial": "DW-SYS-003",
        "price_cents": 1900,
        "pair_sku": "caption-machine",
        "pair_price_cents": 2700,
        "upsell_sku": "caption-machine",
        "upsell_price_cents": 900,
        "cross_sell": ["creator-os", "caption-machine"],
        "sort": 3,
        "name": t("Hook Vault", "خزنة الهوكس", "Hook Vault", "Hook Vault"),
        "sub": t(
            "1,200 hooks sorted by platform and emotion — not a messy notes app.",
            "1,200 هوك مصنّفة حسب المنصة والإحساس.",
            "1 200 hooks classés par plateforme et émotion.",
            "1.200 hooks ordenados por plataforma y emoción.",
        ),
        "headline": t(
            "Open with a line they can’t scroll past.",
            "ابدأ بجملة ما يقدرون يتجاوزونها.",
            "Ouvrez avec une phrase qu’on ne peut pas scroller.",
            "Abre con una línea que no pueden scrollear.",
        ),
        "description": t(
            "TikTok / Snap / Reels / YouTube hooks, pattern interrupts, Arabic + English sets.",
            "هوكس تيك توك وسناب وريلز ويوتيوب، عربي وإنجليزي.",
            "Hooks TikTok / Snap / Reels / YouTube, FR + EN.",
            "Hooks TikTok / Snap / Reels / YouTube, ES + EN.",
        ),
        "contents": t(
            "1,200 hooks · Platform packs · Emotion index · Pattern interrupts · AR + EN",
            "1200 هوك · حسب المنصة · حسب الإحساس · عربي وإنجليزي",
            "1 200 hooks · packs plateforme · index émotion · AR+EN",
            "1.200 hooks · packs de plataforma · índice emocional · AR+EN",
        ),
        "images": imgs("hook-vault"),
        "faq": COMMON_FAQS,
    },
    {
        "sku": "DW-SYS-004",
        "slug": "ai-operator",
        "collection": "ai-command",
        "type": "system",
        "serial": "DW-SYS-004",
        "price_cents": 1900,
        "pair_sku": "offer-engine",
        "pair_price_cents": 3400,
        "upsell_sku": "offer-engine",
        "upsell_price_cents": 1100,
        "cross_sell": ["offer-engine", "time-command"],
        "sort": 4,
        "name": t("AI Operator", "مشغّل الذكاء", "AI Operator", "AI Operator"),
        "sub": t(
            "Stop chatting. Start operating AI like staff.",
            "وقف سوالف مع الشات. شغّل الذكاء كأنه موظف.",
            "Arrêtez de discuter. Faites travailler l’IA comme du staff.",
            "Deja de chatear. Opera la IA como personal.",
        ),
        "headline": t(
            "Make AI behave like staff.",
            "خلّ الذكاء يشتغل كموظف.",
            "Faites se comporter l’IA comme une équipe.",
            "Haz que la IA se comporte como tu equipo.",
        ),
        "description": t(
            "Role briefs, quality gates, weekly cadence, critique loops. Not 5000 prompts.",
            "أدوار، بوابات جودة، إيقاع أسبوعي. مو 5000 برومبت.",
            "Briefs de rôle, gates qualité, cadence. Pas 5000 prompts.",
            "Briefs de rol, quality gates, cadencia. No 5000 prompts.",
        ),
        "contents": t(
            "Role briefs · Quality gates · Weekly cadence · Rewrite loops · Research SOP · Offer agents",
            "أدوار · جودة · إيقاع · إعادة كتابة · بحث · وكلاء العرض",
            "Rôles · qualité · cadence · réécriture · recherche · agents offre",
            "Roles · calidad · cadencia · reescritura · research · agentes de oferta",
        ),
        "images": imgs("ai-operator"),
        "faq": COMMON_FAQS,
    },
    {
        "sku": "DW-SYS-005",
        "slug": "offer-engine",
        "collection": "ai-command",
        "type": "system",
        "serial": "DW-SYS-005",
        "price_cents": 1900,
        "pair_sku": "ai-operator",
        "pair_price_cents": 3400,
        "upsell_sku": "ai-operator",
        "upsell_price_cents": 1100,
        "cross_sell": ["ai-operator", "creator-os"],
        "sort": 5,
        "name": t("Offer Engine", "محرّك العرض", "Offer Engine", "Offer Engine"),
        "sub": t(
            "Price, stack, and say the offer so people stop “thinking about it”.",
            "تسعّر، تركّب، وتقول العرض بحيث القرار يصير سهل.",
            "Prix, stack, phrase d’offre — pour tuer le “je vais réfléchir”.",
            "Precio, stack y frase de oferta — para matar el “lo pienso”.",
        ),
        "headline": t(
            "An offer so clear, “I’ll think about it” dies.",
            "عرض واضح، جملة “بفكر” تموت.",
            "Une offre si claire que “je vais réfléchir” meurt.",
            "Una oferta tan clara que “lo pienso” muere.",
        ),
        "description": t(
            "Offer architecture, value stack, price ladders, objection map, landing skeleton, DM close.",
            "معمار العرض، الستاك، سلالم السعر، الاعتراضات، إغلاق الدردشة.",
            "Architecture d’offre, stack, échelles de prix, objections, close DM.",
            "Arquitectura de oferta, stack, escaleras de precio, objeciones, cierre DM.",
        ),
        "contents": t(
            "Offer architecture · Value stack · Price ladders · Objection map · Landing skeleton · DM close",
            "معمار · ستاك · أسعار · اعتراضات · لاندنق · إغلاق",
            "Architecture · stack · prix · objections · landing · close",
            "Arquitectura · stack · precios · objeciones · landing · cierre",
        ),
        "images": imgs("offer-engine"),
        "faq": COMMON_FAQS,
    },
    {
        "sku": "DW-SYS-006",
        "slug": "wealth-os",
        "collection": "wealth-os",
        "type": "system",
        "serial": "DW-SYS-006",
        "price_cents": 1900,
        "pair_sku": "time-command",
        "pair_price_cents": 3400,
        "upsell_sku": "offer-engine",
        "upsell_price_cents": 1100,
        "cross_sell": ["offer-engine", "time-command"],
        "sort": 6,
        "name": t("Wealth OS", "نظام الثروة", "Wealth OS", "Wealth OS"),
        "sub": t(
            "See your money like an operator, not like a panicked spreadsheet.",
            "فلوسك بصيغة مشغّل، مو إكسل خوف.",
            "Voir l’argent en opérateur, pas en tableur paniqué.",
            "Ver tu dinero como operador, no como Excel de pánico.",
        ),
        "headline": t(
            "Know where your money actually goes.",
            "اعرف فلوسك رايحة وين.",
            "Sachez où va vraiment votre argent.",
            "Sabe a dónde se va tu dinero de verdad.",
        ),
        "description": t(
            "Income streams, spend OS, net-worth pulse, offer P&L, 90-day money map.",
            "دخل، صرف، صافي ثروة، ربح العرض، خارطة 90 يوم.",
            "Revenus, dépenses, net worth, P&L d’offre, carte 90 jours.",
            "Ingresos, gasto, patrimonio, P&L de oferta, mapa 90 días.",
        ),
        "contents": t(
            "Income streams · Spend OS · Net-worth pulse · Offer P&L · 90-day money map",
            "دخل · صرف · صافي · ربح · 90 يوم",
            "Revenus · dépenses · net worth · P&L · 90 jours",
            "Ingresos · gasto · patrimonio · P&L · 90 días",
        ),
        "images": imgs("wealth-os"),
        "faq": COMMON_FAQS,
    },
    {
        "sku": "DW-SYS-007",
        "slug": "glow-ritual",
        "collection": "glow-ritual",
        "type": "system",
        "serial": "DW-SYS-007",
        "price_cents": 1900,
        "pair_sku": "time-command",
        "pair_price_cents": 3400,
        "upsell_sku": "time-command",
        "upsell_price_cents": 1100,
        "cross_sell": ["time-command"],
        "gender": "feminine",
        "sort": 7,
        "name": t("Glow Ritual", "طقوس التوهج", "Rituel Glow", "Ritual Glow"),
        "sub": t(
            "A private ritual system so you stop restarting every Sunday.",
            "طقس خاص، عشان توقفين تبدأين من صفر كل أحد.",
            "Un rituel privé pour arrêter de tout recommencer le dimanche.",
            "Un ritual privado para dejar de reiniciar cada domingo.",
        ),
        "headline": t(
            "Become the woman who doesn’t restart.",
            "صيري اللي ما تبدأ من صفر.",
            "Devenez celle qui ne recommence plus.",
            "Conviértete en la que ya no reinicia.",
        ),
        "description": t(
            "AM/PM ritual, skin/body/mind tracks, photo log, expensive-energy notes, 21-day install.",
            "طقس صباح ومساء، جلد وجسم وذهن، سجل صور، 21 يوم.",
            "Rituel AM/PM, peau/corps/esprit, journal photo, 21 jours.",
            "Ritual AM/PM, piel/cuerpo/mente, diario foto, 21 días.",
        ),
        "contents": t(
            "AM/PM ritual · Skin/body/mind tracks · Photo log · Energy notes · 21-day install",
            "صباح/مساء · جلد/جسم/ذهن · صور · طاقة · 21 يوم",
            "AM/PM · peau/corps/esprit · photos · énergie · 21 jours",
            "AM/PM · piel/cuerpo/mente · fotos · energía · 21 días",
        ),
        "images": imgs("glow-ritual"),
        "faq": COMMON_FAQS,
    },
    {
        "sku": "DW-SYS-008",
        "slug": "time-command",
        "collection": "wealth-os",
        "type": "system",
        "serial": "DW-SYS-008",
        "price_cents": 1900,
        "pair_sku": "wealth-os",
        "pair_price_cents": 3400,
        "upsell_sku": "wealth-os",
        "upsell_price_cents": 1100,
        "cross_sell": ["wealth-os", "ai-operator"],
        "sort": 8,
        "name": t("Time Command", "قيادة الوقت", "Time Command", "Time Command"),
        "sub": t(
            "Attention OS for people whose calendar is lying to them.",
            "نظام انتباه للي أجندته تكذب عليه.",
            "OS attention pour ceux dont le calendrier ment.",
            "OS de atención para quien su calendario le miente.",
        ),
        "headline": t(
            "Take your hours back from your own phone.",
            "خذ ساعاتك من جوالك.",
            "Reprenez vos heures à votre téléphone.",
            "Recupera tus horas de tu propio teléfono.",
        ),
        "description": t(
            "Deep-work blocks, weekly command, second-brain capture, shutdown ritual.",
            "بلوكات عمق، قيادة أسبوعية، التقاط، طقس إغلاق.",
            "Blocs deep work, commande hebdo, capture, rituel de fermeture.",
            "Bloques deep work, mando semanal, captura, ritual de cierre.",
        ),
        "contents": t(
            "Deep-work blocks · Weekly command · Capture · Shutdown ritual",
            "عمق · أسبوع · التقاط · إغلاق",
            "Deep work · semaine · capture · shutdown",
            "Deep work · semana · captura · cierre",
        ),
        "images": imgs("time-command"),
        "faq": COMMON_FAQS,
    },
    {
        "sku": "DW-ADD-001",
        "slug": "caption-machine",
        "collection": "creator-lab",
        "type": "addon",
        "price_cents": 1200,
        "upsell_sku": "hook-vault",
        "upsell_price_cents": 1100,
        "cross_sell": ["hook-vault", "creator-os"],
        "sort": 9,
        "name": t("Caption Machine", "مكينة الكابشنز", "Caption Machine", "Caption Machine"),
        "sub": t("Captions that hold the hook.", "كابشن يمسك الهوك.", "Des légendes qui tiennent le hook.", "Captions que sostienen el hook."),
        "headline": t("Finish the first line.", "كمّل أول سطر.", "Finissez la première ligne.", "Termina la primera línea."),
        "description": t("Platform caption OS for Reels, TikTok, Snap.", "نظام كابشن للريلز والتيك توك والسناب.", "OS légendes Reels, TikTok, Snap.", "OS de captions Reels, TikTok, Snap."),
        "contents": t("Caption frames · Saves CTAs · Platform variants", "إطارات · حفظ · حسب المنصة", "Cadres · CTA save · variantes", "Marcos · CTA save · variantes"),
        "images": imgs("caption-machine"),
        "faq": COMMON_FAQS,
    },
    {
        "sku": "DW-ADD-002",
        "slug": "ad-swipe",
        "collection": "creator-lab",
        "type": "addon",
        "price_cents": 1200,
        "upsell_sku": "faceless-studio",
        "upsell_price_cents": 1100,
        "cross_sell": ["faceless-studio", "offer-engine"],
        "sort": 10,
        "name": t("Ad Creative Swipe", "سوايپ الإعلان", "Ad Creative Swipe", "Ad Creative Swipe"),
        "sub": t("Angles that already paid.", "زوايا دفعوا قبل.", "Des angles qui ont déjà payé.", "Ángulos que ya pagaron."),
        "headline": t("Steal the structure, not the face.", "خذ البنية، مو الوجه.", "Volez la structure, pas le visage.", "Roba la estructura, no la cara."),
        "description": t("Ad structures, hooks, proof stacking for Snap/TikTok.", "بنية إعلان وهوكس وستاك إثبات لسناب وتيك توك.", "Structures pub, hooks, preuve Snap/TikTok.", "Estructuras de anuncio, hooks, prueba Snap/TikTok."),
        "contents": t("Hook · Body · Proof · CTA frames", "هوك · جسم · إثبات · CTA", "Hook · corps · preuve · CTA", "Hook · cuerpo · prueba · CTA"),
        "images": imgs("ad-swipe"),
        "faq": COMMON_FAQS,
    },
    {
        "sku": "DW-ADD-003",
        "slug": "launch-sprint",
        "collection": "ai-command",
        "type": "addon",
        "price_cents": 1200,
        "upsell_sku": "offer-engine",
        "upsell_price_cents": 1100,
        "cross_sell": ["offer-engine", "creator-os"],
        "sort": 11,
        "name": t("30-Day Launch Sprint", "سباق الإطلاق 30 يوم", "Sprint de lancement 30 jours", "Sprint de lanzamiento 30 días"),
        "sub": t("Install the system in 30 days.", "تركّب النظام في 30 يوم.", "Installez le système en 30 jours.", "Instala el sistema en 30 días."),
        "headline": t("A calendar that actually closes.", "تقويم يقفل شغل.", "Un calendrier qui clôture vraiment.", "Un calendario que sí cierra."),
        "description": t("Day-by-day launch map for one offer.", "خارطة إطلاق يوم بيوم لعرض واحد.", "Carte de lancement jour par jour pour une offre.", "Mapa de lanzamiento día a día para una oferta."),
        "contents": t("30-day map · Daily tasks · Review gates", "30 يوم · مهام · بوابات مراجعة", "30 jours · tâches · gates", "30 días · tareas · gates"),
        "images": imgs("launch-sprint"),
        "faq": COMMON_FAQS,
    },
    {
        "sku": "DW-VAULT-001",
        "slug": "the-vault",
        "collection": "the-vault",
        "type": "vault",
        "serial": "DW-VAULT-001",
        "price_cents": 9700,
        "compare_cents": 18800,
        "duo_price_cents": 14900,
        "upsell_sku": None,
        "upsell_price_cents": 6700,
        "cross_sell": [],
        "includes": [
            "DW-SYS-001",
            "DW-SYS-002",
            "DW-SYS-003",
            "DW-SYS-004",
            "DW-SYS-005",
            "DW-SYS-006",
            "DW-SYS-007",
            "DW-SYS-008",
            "DW-ADD-001",
            "DW-ADD-002",
            "DW-ADD-003",
        ],
        "sort": 0,
        "name": t("The Digi World Vault", "خزنة Digi World", "Le Vault Digi World", "El Vault Digi World"),
        "sub": t("All 8 systems + 3 add-ons. One key.", "كل الأنظمة والإضافات. مفتاح واحد.", "Les 8 systèmes + 3 add-ons. Une clé.", "Los 8 sistemas + 3 add-ons. Una llave."),
        "headline": t("The house. Every system. One key.", "الدار كاملة. مفتاح واحد.", "La maison. Tous les systèmes. Une clé.", "La casa. Todos los sistemas. Una llave."),
        "description": t("The complete Digi World house in one vault license.", "دار Digi World كاملة برخصة واحدة.", "Toute la maison Digi World en une licence.", "Toda la casa Digi World en una licencia."),
        "contents": t("8 systems · 3 add-ons · Studio serials · Instant vault", "8 أنظمة · 3 إضافات · أرقام استوديو · خزنة فورية", "8 systèmes · 3 add-ons · n° studio · coffre instantané", "8 sistemas · 3 add-ons · seriales · vault instantáneo"),
        "images": imgs("the-vault"),
        "faq": COMMON_FAQS,
    },
]


REVIEWS = [
    {
        "product_sku": "DW-SYS-001",
        "locale": "en",
        "stars": 5,
        "title": "Finally a system, not a file",
        "body": "I stopped collecting PDFs. This has a start-here. I posted on day one.",
        "display_name": "James",
        "city_country": "LON",
        "source": "studio_preview",
    },
    {
        "product_sku": "DW-SYS-004",
        "locale": "ar",
        "stars": 5,
        "title": "الذكاء صار موظف",
        "body": "وقفت سوالف عشوائية مع الشات. عندي أدوار وإيقاع.",
        "display_name": "سارة",
        "city_country": "RUH",
        "source": "studio_preview",
    },
    {
        "product_sku": "DW-SYS-007",
        "locale": "fr",
        "stars": 5,
        "title": "Plus de dimanche zéro",
        "body": "Le rituel tient. Ce n’est pas un carnet mignon.",
        "display_name": "Camille",
        "city_country": "PAR",
        "source": "studio_preview",
    },
    {
        "product_sku": "DW-SYS-002",
        "locale": "es",
        "stars": 5,
        "title": "Faceless que no parece barato",
        "body": "Por fin un sistema con cara de estudio, no de plantilla.",
        "display_name": "Lucía",
        "city_country": "MAD",
        "source": "studio_preview",
    },
    {
        "product_sku": "DW-VAULT-001",
        "locale": "en",
        "stars": 5,
        "title": "The house is the product",
        "body": "Buying one file was the old me. The vault is the identity.",
        "display_name": "Omar",
        "city_country": "DXB",
        "source": "studio_preview",
    },
    {
        "product_sku": "DW-SYS-005",
        "locale": "en",
        "stars": 5,
        "title": "The offer got simple",
        "body": "I stopped stacking random bonuses. Clarity closed.",
        "display_name": "Nina",
        "city_country": "BER",
        "source": "studio_preview",
    },
]
