from __future__ import annotations

T = dict[str, str]


def t(en: str, ar: str, fr: str, es: str) -> T:
    return {"en": en, "ar": ar, "fr": fr, "es": es}


COLLECTIONS = [
    {
        "slug": "creator-lab",
        "sort": 1,
        "image": "/images/collections/creator-lab.png",
        "name": t("Creator Lab", "مختبر الصانع", "Creator Lab", "Creator Lab"),
        "sub": t(
            "Systems for people who publish.",
            "أنظمة للي ينشرون.",
            "Des systèmes pour ceux qui publient.",
            "Sistemas para quienes publican.",
        ),
    },
    {
        "slug": "ai-command",
        "sort": 2,
        "image": "/images/collections/ai-command.png",
        "name": t("AI Command", "قيادة الذكاء", "AI Command", "AI Command"),
        "sub": t(
            "Operate AI like staff.",
            "شغّل الذكاء كموظف.",
            "Faites travailler l’IA comme une équipe.",
            "Opera la IA como si fuera tu equipo.",
        ),
    },
    {
        "slug": "wealth-os",
        "sort": 3,
        "image": "/images/collections/wealth.png",
        "name": t("Wealth", "الثروة", "Riqueza", "Riqueza"),
        "sub": t(
            "Money and time as an operator.",
            "الفلوس والوقت بصيغة مشغّل.",
            "L’argent et le temps, en opérateur.",
            "Dinero y tiempo, como un operador.",
        ),
    },
    {
        "slug": "glow-ritual",
        "sort": 4,
        "image": "/images/collections/glow.png",
        "name": t("Glow Ritual", "طقوس التوهج", "Rituel Glow", "Ritual Glow"),
        "sub": t(
            "Private luxury rituals.",
            "طقوس خاصة، شكلها غالي.",
            "Des rituels privés, luxe calme.",
            "Rituales privados, lujo silencioso.",
        ),
    },
    {
        "slug": "the-vault",
        "sort": 5,
        "image": "/images/collections/vault.png",
        "name": t("The Vault", "الخزنة", "La Chambre forte", "La Bóveda"),
        "sub": t(
            "The whole house. One key.",
            "الدار كاملة. مفتاح واحد.",
            "Toute la maison. Une clé.",
            "Toda la casa. Una llave.",
        ),
    },
    {
        "slug": "trades-lab",
        "sort": 6,
        "image": "/images/collections/trades-lab.png",
        "name": t("Trades Lab", "مختبر المهن", "Trades Lab", "Trades Lab"),
        "sub": t(
            "Apprenticeship systems for authorized trade work.",
            "أنظمة تدريب للشغل المهني المصرّح.",
            "Des apprentissages pour le métier autorisé.",
            "Aprendizajes para oficios autorizados.",
        ),
    },
]


def imgs(slug: str, n: int = 4) -> list[str]:
    return [f"/images/products/{slug}/{i:02d}.png" for i in range(1, n + 1)]


def faq_block(en_q: str, en_a: str, ar_q: str, ar_a: str, fr_q: str, fr_a: str, es_q: str, es_a: str) -> dict:
    return {
        "en": {"q": en_q, "a": en_a},
        "ar": {"q": ar_q, "a": ar_a},
        "fr": {"q": fr_q, "a": fr_a},
        "es": {"q": es_q, "a": es_a},
    }


PHOTO_FAQS = [
    faq_block(
        "Is this a Notion template I duplicate in one click?",
        "It is a studio operating system: Notion schema, Google Sheets CSVs, a local calculator, SOPs, questionnaires, emails, and a welcome packet. START-HERE is 90 minutes. Not an empty aesthetic dashboard.",
        "هذا قالب نوشن ينسخ بضغطة؟",
        "نظام تشغيل للاستوديو: نوشن، جداول، حاسبة، إجراءات، استبيانات، إيميلات، باقة ترحيب. 90 دقيقة. مو لوحة شكل.",
        "C’est un template Notion en un clic ?",
        "Un OS de studio : Notion, CSV, calculateur, SOP, questionnaires, e-mails. 90 minutes. Pas un dashboard vide.",
        "¿Es una plantilla de Notion de un clic?",
        "Un sistema de estudio: Notion, CSV, calculadora, SOPs, emails. 90 minutos. No un tablero vacío.",
    ),
    faq_block(
        "Do I have to use Notion?",
        "No. Sheets and Notion are both first-class. Copy the CSVs into Google Sheets, or build the board from the Notion schema. Do not rebuild the databases before you set prices.",
        "لازم نوشن؟",
        "لا. الشيتس والنوشن الاثنين أساس. انسخ الـCSV أو ابنِ اللوحة من مخطط نوشن. لا تبني قواعد فاضية قبل الأسعار.",
        "Je dois utiliser Notion ?",
        "Non. Sheets et Notion sont au même niveau. Copiez les CSV, ou construisez le board. Ne reconstruisez pas les bases avant les prix.",
        "¿Tengo que usar Notion?",
        "No. Sheets y Notion van a la par. Copia los CSV o arma el tablero. No reconstruyas bases vacías antes de los precios.",
    ),
    faq_block(
        "Is this a lawyer-drafted contract or a lighting course?",
        "Neither. You get operating checklists, a retainer gate, and a service-agreement skeleton. Counsel in your country reviews the actual agreement. There is no posing or flash lesson in the zip.",
        "هذا عقد محامي أو دورة إضاءة؟",
        "ولا هذا ولا هذا. قوائم تشغيل، بوابة عربون، هيكل اتفاقية. المحامي عندك يراجع العقد. ما فيه درس بوز أو فلاش.",
        "C’est un contrat d’avocat ou un cours lumière ?",
        "Ni l’un ni l’autre. Checklists, acompte, squelette d’accord. Votre conseil relit le contrat. Pas de cours de pose.",
        "¿Es un contrato de abogado o un curso de luz?",
        "Ninguno. Listas de operación, anticipo, esqueleto de acuerdo. Tu abogado revisa el contrato. No hay clase de pose.",
    ),
    faq_block(
        "What is the difference from the Etsy pack?",
        "Etsy is the $49 cousin: inquiry desk, Notion/Sheets, HTML OS. This site zip is the full studio vault — serial DW-SYS-010, duo seats, production and money SOPs, calculator, welcome packet. We do not dump the vault on Etsy.",
        "وش الفرق عن باقة إتسي؟",
        "إتسي ابن عم بـ49$: مكتب استفسار، نوشن/شيتس، نظام HTML. هنا الخزنة كاملة — رقم DW-SYS-010، مقعدين، إنتاج ومال، حاسبة، باقة ترحيب. ما نرمي الخزنة على إتسي.",
        "Quelle différence avec Etsy ?",
        "Etsy est le cousin à 49 $ : inquiry, Notion/Sheets, OS HTML. Ici, le vault complet — serial DW-SYS-010, duo, SOP production et argent. On ne brade pas le vault sur Etsy.",
        "¿Qué cambia frente a Etsy?",
        "Etsy es el primo a 49 $: inquiry, Notion/Sheets, OS HTML. Aquí está el vault completo — serial DW-SYS-010, dúo, SOPs de producción y dinero. No tiramos el vault en Etsy.",
    ),
    faq_block(
        "How many seats? Can I resell it?",
        "One studio is $35. Two seats (you + second shooter or partner) is $55. Personal install only. No redistribution, no Etsy dump of this zip.",
        "كم مقعد؟ أقدر أبيعه؟",
        "استوديو واحد 35$. مقعدين (أنت + مصور ثاني أو شريك) 55$. تركيب شخصي. بدون إعادة نشر، وبدون رمي هذا الزيب على إتسي.",
        "Combien de sièges ? Je peux le revendre ?",
        "Un studio = 35 $. Deux sièges = 55 $. Install perso. Pas de redistribution, pas de dump Etsy de ce zip.",
        "¿Cuántos asientos? ¿Puedo revenderlo?",
        "Un estudio = 35 $. Dos asientos = 55 $. Instalación personal. Sin reventa ni dump en Etsy de este zip.",
    ),
    faq_block(
        "How do I get the files? Refund?",
        "After name and email, the thank-you page has the zip. We also email that inbox. 7-day replacement if the zip is corrupt or will not open. We never sold a certificate.",
        "كيف يوصلني الملف؟ استرجاع؟",
        "بعد الاسم والإيميل، صفحة الشكر فيها الزيب. ونراسل نفس الإيميل. استبدال 7 أيام إذا الملف خربان أو ما ينفتح. ما بعنا شهادة.",
        "Comment je reçois les fichiers ? Remboursement ?",
        "Après nom et e-mail, la page merci a le zip. 7 jours si le zip est corrompu. On n’a jamais vendu un certificat.",
        "¿Cómo recibo los archivos? ¿Reembolso?",
        "Tras nombre y email, la página de gracias tiene el zip. 7 días si el zip está mal o no abre. Nunca vendimos un certificado.",
    ),
]


KEYS_FAQS = [
    faq_block(
        "Is this a theft, bypass, or stolen-vehicle guide?",
        "No. Authorized work for the verified owner (or documented authorized agent) only. Photo ID + registration/title. Log it. Walk away from a bad story. No skipped paperwork, no undocumented immobilizer bypass, no EEPROM attacks, no dealer-login abuse.",
        "هذا دليل سرقة أو تجاوز إيموبيلايزر؟",
        "لا. شغل مصرّح لمالك السيارة المتحقق منه فقط. هوية + استمارة. سجّل. اطلع إذا القصة غلط. ما فيه تجاوز، ولا هجوم EEPROM، ولا إساءة دخول الوكيل.",
        "C’est un guide vol / bypass ?",
        "Non. Travail autorisé pour le propriétaire vérifié seulement. Pièce + carte grise. Journal. On s’arrête si l’histoire cloche. Pas de bypass, pas d’attaque EEPROM, pas d’abus de login concessionnaire.",
        "¿Es una guía de robo o bypass?",
        "No. Trabajo autorizado para el dueño verificado. ID + registro. Bitácora. Si la historia no cuadra, el trabajo termina. Sin bypass, sin ataques EEPROM, sin abuso de login de concesionario.",
    ),
    faq_block(
        "Will it program every car? Do I get a dealer login?",
        "No. The book teaches you to read the car, run supported procedures, and refer luxury platforms you cannot support. There is no dealer-login dump and no ‘works on every VIN’ claim.",
        "يبرمج كل سيارة؟ فيه دخول وكيل؟",
        "لا. تعلّمك تقرأ السيارة، تنفّذ الإجراءات المدعومة، وتحيل المنصات الفخمة اللي ما تدعمها. ما فيه سحب دخول وكيل ولا وعد «على كل فيش».",
        "Ça programme toutes les voitures ? Un login concessionnaire ?",
        "Non. Lire le véhicule, suivre les procédures supportées, transférer le luxe que vous ne tenez pas. Pas de dump de login, pas de « tous les VIN ».",
        "¿Programa todos los coches? ¿Login de concesionario?",
        "No. Leer el coche, seguir procedimientos soportados, derivar lujo que no puedes. Sin dump de login ni «sirve en todo VIN».",
    ),
    faq_block(
        "Do I need a specific programmer before I buy?",
        "You need a legally owned practice vehicle, ownership paperwork, and eventually a real kit. Chapter 8 covers machines and kits with prices so you buy once. The PDF is not a substitute for a tablet or a cutter.",
        "لازم جهاز معيّن قبل الشراء؟",
        "تحتاج سيارة تدريب تملكها قانونياً، أوراق المالك، وبعدين عدة حقيقية. الفصل 8 فيه المكائن والأسعار عشان تشتري مرة. الـPDF مو بديل للجهاز.",
        "Il me faut une machine précise avant d’acheter ?",
        "Véhicule d’entraînement en votre nom, papiers, puis un vrai kit. Le ch. 8 liste machines et prix. Le PDF ne remplace pas la tablette.",
        "¿Necesito una máquina concreta antes de comprar?",
        "Un coche de práctica de tu propiedad, papeles, y luego un kit real. El cap. 8 lista máquinas y precios. El PDF no sustituye la tablet.",
    ),
    faq_block(
        "How many seats? Can I resell the PDF?",
        "One technician is $67. Two shop seats is $97. Personal use. No redistribution, no marketplace dump of this PDF.",
        "كم مقعد؟ أقدر أبيع الـPDF؟",
        "فني واحد 67$. مقعدين للورشة 97$. استخدام شخصي. بدون إعادة نشر وبدون رمي الـPDF على الأسواق.",
        "Combien de sièges ? Je peux revendre le PDF ?",
        "Un tech = 67 $. Deux sièges atelier = 97 $. Usage perso. Pas de redistribution, pas de dump marketplace.",
        "¿Cuántos asientos? ¿Puedo revender el PDF?",
        "Un técnico = 67 $. Dos asientos de taller = 97 $. Uso personal. Sin reventa ni dump en marketplaces.",
    ),
    faq_block(
        "How do I get the files? Refund?",
        "After name and email, the thank-you page has the zip. We also email that inbox. 7-day replacement if the zip is corrupt or will not open. This is not a certificate and not legal advice.",
        "كيف يوصلني الملف؟ استرجاع؟",
        "بعد الاسم والإيميل، صفحة الشكر فيها الزيب. ونراسل نفس الإيميل. استبدال 7 أيام إذا الملف خربان. مو شهادة ومو استشارة قانونية.",
        "Comment je reçois les fichiers ? Remboursement ?",
        "Après nom et e-mail, la page merci a le zip. 7 jours si le zip est corrompu. Pas un certificat, pas un avis juridique.",
        "¿Cómo recibo los archivos? ¿Reembolso?",
        "Tras nombre y email, la página de gracias tiene el zip. 7 días si el zip no abre. No es certificado ni consejo legal.",
    ),
    faq_block(
        "What is in the zip besides the ebook?",
        "START-HERE (how to study, ethics, licence) and Key-Fob-Programming-Mastery.pdf. The 22 chapters, checklists, and packing list live inside the book. We do not ship Car-Key-Programming-Pro as this SKU.",
        "وش داخل الزيب غير الكتاب؟",
        "ابدأ من هنا (دراسة، أخلاق، رخصة) وملف Key-Fob-Programming-Mastery.pdf. الاثنان وعشرون فصلاً والقوائم داخل الكتاب. ما نبيع Car-Key-Programming-Pro كهذا المنتج.",
        "Quoi d’autre dans le zip ?",
        "START-HERE (étude, éthique, licence) et le PDF. Les 22 chapitres sont dans le livre. On ne vend pas Car-Key-Programming-Pro sous ce SKU.",
        "¿Qué más hay en el zip?",
        "START-HERE (estudio, ética, licencia) y el PDF. Los 22 capítulos van en el libro. No vendemos Car-Key-Programming-Pro como este SKU.",
    ),
]


CRM_FAQS = [
    faq_block(
        "Do I need Google Sheets or Notion?",
        "No. Double-click Client-Tracker.html. It runs in your browser. Data stays on this computer in localStorage.",
        "لازم قوقل شيتس أو نوشن؟",
        "لا. افتح Client-Tracker.html. يشتغل بالمتصفح. البيانات تبقى على جهازك.",
        "Il me faut Google Sheets ou Notion ?",
        "Non. Double-cliquez Client-Tracker.html. Ça tourne dans le navigateur. Les données restent sur cet ordinateur.",
        "¿Necesito Google Sheets o Notion?",
        "No. Abre Client-Tracker.html. Corre en el navegador. Los datos se quedan en este ordenador.",
    ),
    faq_block(
        "What are the seven windows?",
        "Setup, Client Database, Communication Log, Task Tracker, Smart Calendar, Client Overview, and Dashboard — one shared data store.",
        "وش السبع نوافذ؟",
        "الإعداد، قاعدة العملاء، سجل التواصل، متتبع المهام، التقويم، نظرة العميل، ولوحة التحكم — مخزن بيانات واحد.",
        "Quelles sont les sept fenêtres ?",
        "Setup, base clients, journal de communication, tâches, calendrier, vue client, et tableau de bord — une seule base.",
        "¿Cuáles son las siete ventanas?",
        "Setup, base de clientes, log de comunicación, tareas, calendario, vista de cliente y panel — un solo almacén.",
    ),
    faq_block(
        "Can I export to CSV / Excel?",
        "Yes. Export CSV exports this window or all data (clients, communications, tasks, setup) with Excel-safe UTF-8 BOM. Setup also imports a clients CSV.",
        "أقدر أصدّر CSV / إكسل؟",
        "نعم. تصدير CSV لهذه النافذة أو لكل البيانات. الإعداد يستورد CSV عملاء أيضاً.",
        "Export CSV / Excel ?",
        "Oui. Export CSV pour la fenêtre ou toutes les données. Setup importe aussi un CSV clients.",
        "¿Puedo exportar a CSV / Excel?",
        "Sí. Export CSV de esta ventana o de todos los datos. Setup también importa un CSV de clientes.",
    ),
    faq_block(
        "How many seats? Can I resell it?",
        "One studio is $39. Two seats is $59. Personal use. No redistribution, no marketplace dump of the HTML.",
        "كم مقعد؟ أقدر أبيعه؟",
        "استوديو واحد 39$. مقعدين 59$. استخدام شخصي. بدون إعادة نشر.",
        "Combien de sièges ? Je peux le revendre ?",
        "Un studio = 39 $. Deux sièges = 59 $. Usage perso. Pas de redistribution.",
        "¿Cuántos asientos? ¿Puedo revenderlo?",
        "Un estudio = 39 $. Dos asientos = 59 $. Uso personal. Sin reventa.",
    ),
    faq_block(
        "How do I get the files? Refund?",
        "After name and email, the thank-you page has the zip. We also email that inbox. 7-day replacement if the zip will not open.",
        "كيف يوصلني الملف؟ استرجاع؟",
        "بعد الاسم والإيميل، صفحة الشكر فيها الزيب. استبدال 7 أيام إذا ما ينفتح.",
        "Comment je reçois les fichiers ?",
        "Après nom et e-mail, la page merci a le zip. 7 jours si le zip n’ouvre pas.",
        "¿Cómo recibo los archivos?",
        "Tras nombre y email, la página de gracias tiene el zip. 7 días si no abre.",
    ),
]


INVOICE_FAQS = [
    faq_block(
        "Do I need QuickBooks, Wave, or Google Sheets?",
        "No. Double-click Invoice-Quote-Desk.html. Quotes and invoices stay in localStorage on this computer.",
        "لازم كويك بوكس أو ويف أو قوقل شيتس؟",
        "لا. افتح Invoice-Quote-Desk.html. العروض والفواتير تبقى على جهازك.",
        "Il me faut QuickBooks, Wave ou Google Sheets ?",
        "Non. Double-cliquez Invoice-Quote-Desk.html. Devis et factures restent en localStorage.",
        "¿Necesito QuickBooks, Wave o Google Sheets?",
        "No. Abre Invoice-Quote-Desk.html. Presupuestos y facturas quedan en localStorage.",
    ),
    faq_block(
        "Can I turn a quote into an invoice?",
        "Yes. Accept the quote, then Convert — line items, client, and totals carry over. Edit before you send.",
        "أقدر أحّول العرض لفاتورة؟",
        "نعم. اقبل العرض ثم حوّل — البنود والعميل والمجاميع تنتقل. عدّل قبل الإرسال.",
        "Je peux convertir un devis en facture ?",
        "Oui. Acceptez le devis, puis Convertir — lignes, client et totaux suivent. Modifiez avant d’envoyer.",
        "¿Puedo convertir un presupuesto en factura?",
        "Sí. Acepta el presupuesto y convierte — líneas, cliente y totales pasan. Edita antes de enviar.",
    ),
    faq_block(
        "How do I get a PDF?",
        "Open the document → Print → Save as PDF. Your business name, tax, and payment note print on the page.",
        "كيف أحصل على PDF؟",
        "افتح المستند → طباعة → حفظ كـ PDF. اسم النشاط والضريبة وملاحظة الدفع تطبع على الصفحة.",
        "Comment obtenir un PDF ?",
        "Ouvrez le document → Imprimer → Enregistrer en PDF. Nom, taxe et note de paiement s’impriment.",
        "¿Cómo saco un PDF?",
        "Abre el documento → Imprimir → Guardar como PDF. Nombre, impuesto y nota de pago salen en la página.",
    ),
    faq_block(
        "How many seats? Can I resell it?",
        "One studio is $29. Two seats is $45. Personal use. No redistribution, no marketplace dump of the HTML.",
        "كم مقعد؟ أقدر أبيعه؟",
        "استوديو واحد 29$. مقعدين 45$. استخدام شخصي. بدون إعادة نشر.",
        "Combien de sièges ? Je peux le revendre ?",
        "Un studio = 29 $. Deux sièges = 45 $. Usage perso. Pas de redistribution.",
        "¿Cuántos asientos? ¿Puedo revenderlo?",
        "Un estudio = 29 $. Dos asientos = 45 $. Uso personal. Sin reventa.",
    ),
    faq_block(
        "How do I get the files? Refund?",
        "After name and email, the thank-you page has the zip. We also email that inbox. 7-day replacement if the zip will not open.",
        "كيف يوصلني الملف؟ استرجاع؟",
        "بعد الاسم والإيميل، صفحة الشكر فيها الزيب. استبدال 7 أيام إذا ما ينفتح.",
        "Comment je reçois les fichiers ?",
        "Après nom et e-mail, la page merci a le zip. 7 jours si le zip n’ouvre pas.",
        "¿Cómo recibo los archivos?",
        "Tras nombre y email, la página de gracias tiene el zip. 7 días si no abre.",
    ),
]


PRODUCTS = [
    {
        "sku": "DW-SYS-010",
        "slug": "photographer-os",
        "collection": "creator-lab",
        "type": "system",
        "serial": "DW-SYS-010",
        "price_cents": 3500,
        "duo_price_cents": 5500,
        "cross_sell": [],
        "license_pool": 250,
        "sort": 0,
        "name": t(
            "Photographer Client Studio",
            "استوديو عملاء المصور",
            "Studio client photographe",
            "Estudio de clientes para fotógrafos",
        ),
        "headline": t(
            "A Saturday is inventory. Stop leaking it.",
            "السبت مخزون. وقف تسرّبه.",
            "Un samedi est un stock. Arrêtez de le brader.",
            "Un sábado es inventario. Deja de regalarlo.",
        ),
        "sub": t(
            "The 90-minute desk for wedding and commercial photographers who leak jobs in DMs and hours in ‘unlimited’ galleries.",
            "مكتب 90 دقيقة لمصوري الأعراس والتجاري اللي يضيّعون الشغل في الخاص والساعات في معارض «بدون حد».",
            "Le bureau 90 minutes pour photographes mariage et commercial qui perdent les jobs en DM et les heures en galeries « illimitées ».",
            "El escritorio de 90 minutos para fotógrafos de boda y comercial que pierden trabajos en DMs y horas en galerías «ilimitadas».",
        ),
        "description": t(
            "This is the operating system of a photography studio that books, shoots, delivers, and collects.\n\nGeneric freelancer CRMs fail photographers because a wedding is not a logo project. Dates are inventory. Saturdays are finite. Usage rights are where commercial profit lives.\n\nInstall in order: true-hourly math → rate card → board → 15-minute inquiry → retainer gate → 15-minute formals → revision cap → paid-in-full gallery → invoices. Sheets and Notion are both first-class. The local calculator shows a bad package before you send it.",
            "هذا نظام تشغيل استوديو تصوير يحجز، يصور، يسلّم، ويحصّل.\n\nقوالب الفريلانسر العامة تفشل المصور لأن العرس مو مشروع لوقو. التواريخ مخزون. السبت محدود. حقوق الاستخدام هي ربح التجاري.\n\nركّب بالترتيب: الساعة الحقيقية → التسعيرة → اللوحة → رد 15 دقيقة → بوابة العربون → الفورمالز → حد التعديل → المعرض بعد السداد → الفواتير. الشيتس والنوشن الاثنين أساس.",
            "C’est l’OS d’un studio qui réserve, shoot, livre et encaisse.\n\nUn CRM freelance générique rate le photographe : un mariage n’est pas un logo. Les samedis sont un stock. Les droits d’usage font le profit commercial.\n\nInstaller dans l’ordre : tarif horaire réel → grille → board → réponse 15 min → acompte → formelles → plafond de retouches → galerie soldée → factures.",
            "Es el sistema de un estudio que reserva, dispara, entrega y cobra.\n\nUn CRM genérico de freelance falla: una boda no es un logo. Los sábados son inventario. Los derechos de uso son el margen comercial.\n\nInstala en orden: tarifa real → lista → tablero → respuesta 15 min → anticipo → formales → tope de revisiones → galería pagada → facturas.",
        ),
        "contents": t(
            "START-HERE (90 min)\nStudio math + Monday rhythm + Notion schema\n15-minute inquiry, qualifier, objections\nPackages, usage rights, rate CSV + local calculator\nBooking SOP, questionnaires, 15-min formals, retainer gate\nWedding-day production, shot lists, second shooter\nGallery, revision cap, raws, prints\nInvoices, chase scripts, money log\nSheets boards + welcome packet + emails",
            "ابدأ من هنا (90 د)\nحساب الاستوديو + إيقاع الاثنين + مخطط نوشن\nرد 15 دقيقة، تصفية، اعتراضات\nباقات، استخدام، CSV تسعيرة + حاسبة\nحجز، استبيانات، فورمالز، عربون\nإنتاج يوم العرس، لقطات، مصور ثاني\nمعرض، حد تعديل، ملفات خام، طباعة\nفواتير، ملاحقة، سجل مال\nلوحات شيتس + باقة ترحيب + إيميلات",
            "START-HERE (90 min)\nMath studio + lundi + schéma Notion\nInquiry 15 min, filtre, objections\nOffres, usage, CSV tarifs + calculateur\nBooking, questionnaires, formelles, acompte\nJour J, listes de plans, second shooter\nGalerie, plafond retouches, RAW, tirages\nFactures, relances, journal\nBoards Sheets + welcome + e-mails",
            "START-HERE (90 min)\nCuentas del estudio + lunes + esquema Notion\nInquiry 15 min, filtro, objeciones\nPaquetes, uso, CSV de tarifas + calculadora\nReserva, cuestionarios, formales, anticipo\nDía de boda, listas, segundo disparador\nGalería, tope de revisiones, RAW, copias\nFacturas, cobro, registro\nTableros Sheets + bienvenida + emails",
        ),
        "images": imgs("photographer-os"),
        "faq": PHOTO_FAQS,
    },
    {
        "sku": "DW-EBK-001",
        "slug": "key-fob-programming-mastery",
        "collection": "trades-lab",
        "type": "system",
        "serial": "DW-EBK-001",
        "price_cents": 6700,
        "duo_price_cents": 9700,
        "cross_sell": [],
        "license_pool": 250,
        "sort": 1,
        "name": t(
            "Key Fob Programming Mastery",
            "إتقان برمجة ريموت السيارة",
            "Maîtrise de la programmation de télécommandes",
            "Dominio de la programación de mandos",
        ),
        "headline": t(
            "Program the spare. Prove the owner. Leave the shortcuts alone.",
            "برمج الاحتياطي. ثبّت المالك. اترك الاختصارات.",
            "Programmez la copie. Prouvez le propriétaire. Laissez les raccourcis.",
            "Programa el recambio. Prueba al dueño. Deja los atajos.",
        ),
        "sub": t(
            "Complete visual apprenticeship for authorized key-fob and immobilizer work: verify the owner, quote the job, prep the remote, run the procedure, test the finish, refer what you cannot support.",
            "تدريب بصري كامل لبرمجة الريموت والإيموبيلايزر المصرّح: تحقق من المالك، سعّر الشغل، حضّر الريموت، نفّذ الإجراء، اختبر النهاية، وأحل ما لا تدعمه.",
            "Apprentissage visuel complet pour télécommandes et antivol autorisés : vérifier le propriétaire, chiffrer, préparer, programmer, tester, transférer ce que vous ne tenez pas.",
            "Aprendizaje visual completo para mando e inmovilizador autorizado: verifica al dueño, cotiza, prepara, programa, prueba, deriva lo que no puedas.",
        ),
        "description": t(
            "This is a trade apprenticeship in PDF form — authorized automotive key-fob work for verified vehicle owners only.\n\nYou do not become competent by skimming a YouTube dare. You verify the owner, quote Add Key vs All Keys Lost, prepare the remote, follow the procedure, test the finish, and refer what you cannot support.\n\nWeak vehicle batteries brick more jobs than bad technicians. Luxury platforms get a referral, not a miracle. This product does not teach theft, skipped paperwork, stolen-vehicle starts, undocumented immobilizer bypass, EEPROM attacks, or dealer-login abuse.",
            "هذا تدريب مهني بصيغة PDF — شغل ريموت مصرّح لمالك السيارة المتحقق منه فقط.\n\nما تصير كفء بتقليد يوتيوب. تتحقق من المالك، تسعّر إضافة مفتاح مقابل كل المفاتيح ضائعة، تحضّر الريموت، تتبع الإجراء، تختبر، وتحيل اللي ما تدعمه.\n\nالبطارية الضعيفة تخرب شغل أكثر من الفني الغلط. المنصات الفخمة تُحال، مو معجزة. هذا المنتج ما يعلّم سرقة ولا تجاوز إيموبيلايزر ولا هجوم EEPROM ولا إساءة دخول الوكيل.",
            "Un apprentissage de métier en PDF — travail autorisé sur télécommande pour le propriétaire vérifié seulement.\n\nOn ne devient pas compétent en copiant YouTube. Vérifier le propriétaire, chiffrer Add Key vs All Keys Lost, préparer, suivre, tester, transférer.\n\nUne batterie faible brique plus de jobs qu’un mauvais tech. Le luxe se transmet, il ne se « miracle » pas. Pas de vol, pas de bypass, pas d’attaque EEPROM, pas d’abus de login concessionnaire.",
            "Un aprendizaje de oficio en PDF — trabajo autorizado de mando para el dueño verificado.\n\nNo te haces competente imitando YouTube. Verifica al dueño, cotiza Add Key vs All Keys Lost, prepara, sigue el procedimiento, prueba, deriva.\n\nUna batería débil rompe más trabajos que un mal técnico. El lujo se deriva, no se inventa. No enseña robo, bypass, ataques EEPROM ni abuso de login de concesionario.",
        ),
        "contents": t(
            "START-HERE (study path, ethics, licence)\n22-chapter illustrated field manual (PDF)\nLaw, ethics, paperwork — ID + registration before OBD\nFob anatomy, immobilizers, RKE vs smart vs blade+chip\nMachines, kits, consumables (with prices)\nProcedure A — Add a spare\nProcedure B — Lost remote, car present\nProcedure C — All Keys Lost\nCutting, programming discipline, testing, fault-finding\nLuxury limits & referral · pricing the customer\n90-day competence calendar · glossary · packing list",
            "ابدأ من هنا (دراسة، أخلاق، رخصة)\nدليل ميداني مصوّر 22 فصلاً (PDF)\nقانون وأوراق — هوية + استمارة قبل أي كتابة\nتشريح الريموت، إيموبيلايزر، أنواع المفاتيح\nمكائن وعدد وأسعار\nإجراء أ — إضافة احتياطي\nإجراء ب — ريموت ضائع والسيارة موجودة\nإجراء ج — كل المفاتيح ضائعة\nقص، انضباط برمجة، اختبار، أعطال\nحدود الفخم والإحالة · تسعير العميل\nمسار 90 يوم · قاموس · قائمة تعبئة",
            "START-HERE (étude, éthique, licence)\nManuel illustré 22 chapitres (PDF)\nDroit et papiers — pièce + carte grise avant l’OBD\nAnatomie, antivol, types de clés\nMachines, kits, consommables (prix)\nProcédure A — ajouter une copie\nProcédure B — télécommande perdue, véhicule présent\nProcédure C — All Keys Lost\nTaille, discipline, tests, pannes\nLimites luxe & transfert · prix client\nCalendrier 90 jours · glossaire · packing",
            "START-HERE (estudio, ética, licencia)\nManual ilustrado 22 capítulos (PDF)\nLey y papeles — ID + registro antes del OBD\nAnatomía, inmovilizador, tipos de mando\nMáquinas, kits, consumibles (precios)\nProcedimiento A — añadir recambio\nProcedimiento B — mando perdido, coche presente\nProcedimiento C — All Keys Lost\nCorte, disciplina, prueba, fallos\nLímites de lujo y derivación · precio al cliente\nCalendario 90 días · glosario · packing",
        ),
        "images": imgs("key-fob-programming-mastery", 10),
        "faq": KEYS_FAQS,
    },
    {
        "sku": "DW-SYS-011",
        "slug": "client-tracker",
        "collection": "creator-lab",
        "type": "system",
        "serial": "DW-SYS-011",
        "price_cents": 3900,
        "duo_price_cents": 5900,
        "cross_sell": [],
        "license_pool": 250,
        "sort": 2,
        "name": t(
            "Digi World Client Tracker",
            "متتبع عملاء ديجي وورلد",
            "Client Tracker Digi World",
            "Client Tracker Digi World",
        ),
        "headline": t(
            "Clients, follow-ups, tasks, invoices — one desk.",
            "عملاء، متابعات، مهام، فواتير — مكتب واحد.",
            "Clients, relances, tâches, factures — un bureau.",
            "Clientes, seguimientos, tareas, facturas — un escritorio.",
        ),
        "sub": t(
            "Offline HTML CRM: Client Database, Communication Log, Task Tracker, Smart Calendar, Client Overview, Dashboard — with CSV export. No Google account.",
            "CRM HTML بدون إنترنت: قاعدة عملاء، سجل تواصل، مهام، تقويم، نظرة عميل، لوحة — مع تصدير CSV. بدون حساب قوقل.",
            "CRM HTML hors ligne : base clients, journal, tâches, calendrier, vue client, dashboard — export CSV. Pas de compte Google.",
            "CRM HTML sin cuenta Google: base de clientes, log, tareas, calendario, vista y panel — con export CSV.",
        ),
        "description": t(
            "A freelancer’s desk that actually keeps the follow-up alive.\n\nSeven windows share one local store: Setup, Client Database, Communication Log, Task Tracker, Smart Calendar, Client Overview, Dashboard. Charts update when you add a row. Export CSV for this window or the whole desk. Import clients from CSV on Setup.\n\nNo Google Sheets. No Notion login. Double-click the HTML and work. Data stays on this computer.",
            "مكتب فريلانسر يحافظ على المتابعة.\n\nسبع نوافذ على مخزن محلي واحد. الرسوم تتحدّث مع كل صف. صدّر CSV. استورد عملاء من CSV.\n\nبدون قوقل شيتس. افتح الـHTML واشتغل. البيانات على جهازك.",
            "Un bureau freelance qui garde les relances vivantes.\n\nSept fenêtres, une base locale. Les graphiques suivent. Export CSV. Import clients.\n\nPas de Google Sheets. Double-cliquez le HTML. Les données restent ici.",
            "Un escritorio freelance que mantiene el seguimiento vivo.\n\nSiete ventanas, un almacén local. Los gráficos se actualizan. Export CSV. Importa clientes.\n\nSin Google Sheets. Abre el HTML. Los datos se quedan aquí.",
        ),
        "contents": t(
            "START-HERE\nClient-Tracker.html (7 windows)\nSetup with editable dropdowns\nClient Database + charts\nCommunication Log\nTask Tracker (KPIs, overdue, filters)\nSmart Calendar (tasks, actions, contracts)\nClient Overview (360°)\nDashboard\nExport / import CSV\nSample desk included",
            "ابدأ من هنا\nClient-Tracker.html (7 نوافذ)\nإعداد القوائم\nقاعدة عملاء + رسوم\nسجل تواصل\nمهام (مؤشرات، متأخر، فلاتر)\nتقويم ذكي\nنظرة عميل\nلوحة تحكم\nتصدير/استيراد CSV\nبيانات تجريبية",
            "START-HERE\nClient-Tracker.html (7 fenêtres)\nSetup listes\nBase clients + graphiques\nJournal de communication\nTâches (KPI, retard, filtres)\nCalendrier\nVue client\nDashboard\nExport / import CSV\nDonnées exemple",
            "START-HERE\nClient-Tracker.html (7 ventanas)\nSetup listas\nBase de clientes + gráficos\nLog de comunicación\nTareas (KPI, vencidas, filtros)\nCalendario\nVista de cliente\nPanel\nExport / import CSV\nDatos de ejemplo",
        ),
        "images": imgs("client-tracker", 11),
        "faq": CRM_FAQS,
    },
    {
        "sku": "DW-SYS-012",
        "slug": "invoice-desk",
        "collection": "creator-lab",
        "type": "system",
        "serial": "DW-SYS-012",
        "price_cents": 2900,
        "duo_price_cents": 4500,
        "cross_sell": ["DW-SYS-011"],
        "license_pool": 250,
        "sort": 1,
        "name": t(
            "Quote & Invoice Desk",
            "مكتب العروض والفواتير",
            "Bureau devis & factures",
            "Escritorio de presupuestos y facturas",
        ),
        "headline": t(
            "Quote. Invoice. Get paid.",
            "عرض. فاتورة. حصّل.",
            "Devis. Facture. Encaissez.",
            "Presupuesto. Factura. Cobra.",
        ),
        "sub": t(
            "Offline HTML money desk: quotes → invoices → paid. Print PDF. No QuickBooks login. Complements Client Tracker.",
            "مكتب مال HTML بدون إنترنت: عروض → فواتير → مدفوع. اطبع PDF. بدون كويك بوكس. يكمل متتبع العملاء.",
            "Bureau argent HTML hors ligne : devis → factures → payé. PDF. Pas de QuickBooks. Complète Client Tracker.",
            "Escritorio HTML offline: presupuestos → facturas → pagado. PDF. Sin QuickBooks. Complementa Client Tracker.",
        ),
        "description": t(
            "Freelancers lose money in Word invoices and half-sent quotes.\n\nOne HTML desk: Setup your brand, tax, and payment note. Build quotes with line items. Convert an accepted quote into an invoice. Mark paid when the wire lands. Print or Save as PDF for the client.\n\nDashboard shows open quotes, unpaid, overdue, and outstanding. Data stays in localStorage — Digi World never sees your clients or amounts.\n\nPairs with Client Tracker for the relationship desk; this one is the money desk.",
            "الفريلانسر يضيّع فلوس في فواتير وورد وعروض نصف مرسلة.\n\nمكتب HTML واحد: إعداد العلامة والضريبة وملاحظة الدفع. ابنِ عروض ببنود. حوّل العرض المقبول لفاتورة. علّم مدفوع لما يوصل التحويل. اطبع أو احفظ PDF.\n\nاللوحة تعرض العروض المفتوحة وغير المدفوع والمتأخر والمستحق. البيانات محلية.\n\nيكمل متتبع العملاء للعلاقات؛ هذا مكتب المال.",
            "Les freelances perdent de l’argent dans Word et des devis à moitié envoyés.\n\nUn bureau HTML : marque, taxe, note de paiement. Devis avec lignes. Convertissez un devis accepté en facture. Marquez payé. Imprimez ou PDF.\n\nLe dashboard montre devis ouverts, impayés, retard, encours. Données locales.\n\nComplète Client Tracker ; ici, c’est l’argent.",
            "Los freelancers pierden dinero en facturas Word y presupuestos a medias.\n\nUn escritorio HTML: marca, impuesto, nota de pago. Presupuestos con líneas. Convierte uno aceptado en factura. Marca pagado. Imprime o PDF.\n\nEl panel muestra abiertos, impagos, vencidos y pendiente. Datos locales.\n\nComplementa Client Tracker; este es el escritorio del dinero.",
        ),
        "contents": t(
            "START-HERE\nInvoice-Quote-Desk.html\nSetup (brand, tax, currency, payment note)\nDashboard (open / unpaid / overdue)\nQuotes with line items + status\nConvert quote → invoice\nInvoices + Mark paid\nPrint / Save as PDF\nSample desk included",
            "ابدأ من هنا\nInvoice-Quote-Desk.html\nإعداد (علامة، ضريبة، عملة، ملاحظة دفع)\nلوحة (مفتوح / غير مدفوع / متأخر)\nعروض ببنود + حالة\nتحويل عرض → فاتورة\nفواتير + تعليم مدفوع\nطباعة / حفظ PDF\nبيانات تجريبية",
            "START-HERE\nInvoice-Quote-Desk.html\nSetup (marque, taxe, devise, note)\nDashboard (ouverts / impayés / retard)\nDevis + lignes + statut\nConvertir devis → facture\nFactures + Marquer payé\nImprimer / PDF\nDonnées exemple",
            "START-HERE\nInvoice-Quote-Desk.html\nSetup (marca, impuesto, moneda, nota)\nPanel (abiertos / impagos / vencidos)\nPresupuestos + líneas + estado\nConvertir presupuesto → factura\nFacturas + Marcar pagado\nImprimir / PDF\nDatos de ejemplo",
        ),
        "images": imgs("invoice-desk", 7),
        "faq": INVOICE_FAQS,
    },
]

REVIEWS = [
    {
        "product_sku": "DW-SYS-010",
        "locale": "en",
        "stars": 5,
        "title": "Saturdays were being given away",
        "body": "Built against a wedding studio that quoted ‘it depends’ in DMs and then worked a 12-hour Saturday at portrait-session money. The kit treats the date as inventory before the inquiry is answered.",
        "display_name": "Studio brief",
        "city_country": "Wedding desk",
        "source": "studio_preview",
    },
    {
        "product_sku": "DW-SYS-010",
        "locale": "en",
        "stars": 5,
        "title": "Gallery opened before the balance",
        "body": "Commercial jobs leaked when the preview link went live and the invoice sat. Retainer gate + paid-in-full gallery is the rule the pack is written around — not a prettier CRM skin.",
        "display_name": "Studio brief",
        "city_country": "Brand / commercial",
        "source": "studio_preview",
    },
    {
        "product_sku": "DW-SYS-010",
        "locale": "en",
        "stars": 5,
        "title": "Unlimited revisions is not a package",
        "body": "Two rounds on the preview set, extra rounds priced, ‘make it more magical’ sent back to frame numbers. That is the leak this desk was designed to close.",
        "display_name": "Studio brief",
        "city_country": "Portrait + wedding",
        "source": "studio_preview",
    },
    {
        "product_sku": "DW-SYS-010",
        "locale": "ar",
        "stars": 5,
        "title": "السبت كان يتوزّع مجان",
        "body": "مبني ضد استوديو أعراس يرد «حسب» في الخاص ويشتغل 12 ساعة بفلوس جلسة بورتريه. التاريخ مخزون قبل ما ينرد الاستفسار.",
        "display_name": "موجز استوديو",
        "city_country": "مكتب أعراس",
        "source": "studio_preview",
    },
    {
        "product_sku": "DW-SYS-010",
        "locale": "fr",
        "stars": 5,
        "title": "La galerie partait avant le solde",
        "body": "Jobs commercial fuitaient dès le lien preview. L’acompte et la galerie soldée sont la règle — pas un CRM joli.",
        "display_name": "Brief studio",
        "city_country": "Brand / commercial",
        "source": "studio_preview",
    },
    {
        "product_sku": "DW-SYS-010",
        "locale": "es",
        "stars": 5,
        "title": "Revisiones ilimitadas no es un paquete",
        "body": "Dos rondas en el preview, extras con precio, «más mágico» vuelve a números de frame. Esa fuga es la que cierra el escritorio.",
        "display_name": "Brief de estudio",
        "city_country": "Retrato + boda",
        "source": "studio_preview",
    },
    {
        "product_sku": "DW-EBK-001",
        "locale": "en",
        "stars": 5,
        "title": "All Keys Lost is not a YouTube dare",
        "body": "Built against a van that quoted All Keys Lost from a clip, then learned the working key was in a drawer. Add Key first. Paperwork first. The book is written in that order.",
        "display_name": "Field brief",
        "city_country": "Mobile auto-key",
        "source": "studio_preview",
    },
    {
        "product_sku": "DW-EBK-001",
        "locale": "en",
        "stars": 5,
        "title": "Weak battery, not a bricked module",
        "body": "A job that looked like a dead immobilizer was a dying support pack. The callout colors in the manual are the point: power first, then write.",
        "display_name": "Field brief",
        "city_country": "Shop bay",
        "source": "studio_preview",
    },
    {
        "product_sku": "DW-EBK-001",
        "locale": "en",
        "stars": 5,
        "title": "Refer the platform you cannot support",
        "body": "Luxury limits are a chapter, not a comment. Walk away beats inventing a miracle on an unsupported cluster.",
        "display_name": "Field brief",
        "city_country": "Locksmith desk",
        "source": "studio_preview",
    },
    {
        "product_sku": "DW-EBK-001",
        "locale": "ar",
        "stars": 5,
        "title": "كل المفاتيح ضائعة مو تحدّي يوتيوب",
        "body": "مبني ضد ورشة تسعّر All Keys Lost من مقطع، والمفتاح الشغّال في الدرج. إضافة مفتاح أولاً. الأوراق أولاً. الكتاب بهذا الترتيب.",
        "display_name": "موجز ميدان",
        "city_country": "مفتاح متنقّل",
        "source": "studio_preview",
    },
    {
        "product_sku": "DW-EBK-001",
        "locale": "fr",
        "stars": 5,
        "title": "Batterie faible, pas un module brické",
        "body": "Un job « antivol mort » était un pack de soutien à plat. Les encadrés du manuel : alimenter d’abord, écrire ensuite.",
        "display_name": "Brief terrain",
        "city_country": "Baie atelier",
        "source": "studio_preview",
    },
    {
        "product_sku": "DW-EBK-001",
        "locale": "es",
        "stars": 5,
        "title": "Deriva la plataforma que no sostienes",
        "body": "Los límites de lujo son un capítulo, no un comentario. Marcharse gana a inventar un milagro en un cluster no soportado.",
        "display_name": "Brief de campo",
        "city_country": "Mesa de cerrajería",
        "source": "studio_preview",
    },
    {
        "product_sku": "DW-SYS-011",
        "locale": "en",
        "stars": 5,
        "title": "Follow-up lived in three apps",
        "body": "Built against a freelance desk that kept clients in Notes, tasks in a chat, and invoices in a folder. One HTML desk. CSV when the accountant asks.",
        "display_name": "Studio brief",
        "city_country": "Freelance desk",
        "source": "studio_preview",
    },
    {
        "product_sku": "DW-SYS-011",
        "locale": "en",
        "stars": 5,
        "title": "No Google account to start",
        "body": "Open the file tonight. Sample clients already make the Dashboard look alive. Then replace them with your real book.",
        "display_name": "Studio brief",
        "city_country": "Agency start",
        "source": "studio_preview",
    },
    {
        "product_sku": "DW-SYS-011",
        "locale": "ar",
        "stars": 5,
        "title": "المتابعة كانت في ثلاث تطبيقات",
        "body": "مبني ضد مكتب فريلانسر: العملاء في الملاحظات، المهام في الشات، الفواتير في مجلد. مكتب HTML واحد. CSV للمحاسب.",
        "display_name": "موجز استوديو",
        "city_country": "مكتب فريلانسر",
        "source": "studio_preview",
    },
    {
        "product_sku": "DW-SYS-012",
        "locale": "en",
        "stars": 5,
        "title": "Quotes lived in WhatsApp",
        "body": "Built against a desk that typed totals in chat and redid the math in Word. One HTML: quote, convert, print PDF, mark paid.",
        "display_name": "Studio brief",
        "city_country": "Freelance desk",
        "source": "studio_preview",
    },
    {
        "product_sku": "DW-SYS-012",
        "locale": "en",
        "stars": 5,
        "title": "Overdue was a feeling",
        "body": "Open the Dashboard — unpaid and overdue are numbers, not a vague sense that someone still owes you.",
        "display_name": "Studio brief",
        "city_country": "Agency start",
        "source": "studio_preview",
    },
    {
        "product_sku": "DW-SYS-012",
        "locale": "ar",
        "stars": 5,
        "title": "العروض كانت في واتساب",
        "body": "مبني ضد مكتب يكتب المبالغ في الشات ويعيد الحساب في وورد. HTML واحد: عرض، تحويل، PDF، مدفوع.",
        "display_name": "موجز استوديو",
        "city_country": "مكتب فريلانسر",
        "source": "studio_preview",
    },
]
