import type { Catalog } from "./types";

const L = (en: string, ar: string, fr: string, es: string) => ({ en, ar, fr, es });

export const FALLBACK_CATALOG: Catalog = {
  drop: "Drop 01 — 2026",
  currency: "USD",
  licenses_issued: 0,
  collections: [
    { slug: "creator-lab", sort: 1, image: "/images/collections/creator-lab.png", name: L("Creator Lab", "مختبر الصانع", "Creator Lab", "Creator Lab"), sub: L("Systems for people who publish.", "أنظمة للي ينشرون.", "Des systèmes pour ceux qui publient.", "Sistemas para quienes publican.") },
    { slug: "ai-command", sort: 2, image: "/images/collections/ai-command.png", name: L("AI Command", "قيادة الذكاء", "AI Command", "AI Command"), sub: L("Operate AI like staff.", "شغّل الذكاء كموظف.", "Faites travailler l’IA comme une équipe.", "Opera la IA como si fuera tu equipo.") },
    { slug: "wealth-os", sort: 3, image: "/images/collections/wealth.png", name: L("Wealth", "الثروة", "Riqueza", "Riqueza"), sub: L("Money and time as an operator.", "الفلوس والوقت بصيغة مشغّل.", "L’argent et le temps, en opérateur.", "Dinero y tiempo, como un operador.") },
    { slug: "glow-ritual", sort: 4, image: "/images/collections/glow.png", name: L("Glow Ritual", "طقوس التوهج", "Rituel Glow", "Ritual Glow"), sub: L("Private luxury rituals.", "طقوس خاصة، شكلها غالي.", "Des rituels privés, luxe calme.", "Rituales privados, lujo silencioso.") },
    { slug: "the-vault", sort: 5, image: "/images/collections/vault.png", name: L("The Vault", "الخزنة", "La Chambre forte", "La Bóveda"), sub: L("The whole house. One key.", "الدار كاملة. مفتاح واحد.", "Toute la maison. Une clé.", "Toda la casa. Una llave.") },
    { slug: "trades-lab", sort: 6, image: "/images/collections/trades-lab.png", name: L("Trades Lab", "مختبر المهن", "Trades Lab", "Trades Lab"), sub: L("Apprenticeship systems for authorized trade work.", "أنظمة تدريب للشغل المهني المصرّح.", "Des apprentissages pour le métier autorisé.", "Aprendizajes para oficios autorizados.") },
  ],
  reviews: [
    {
      product_sku: "DW-SYS-010",
      locale: "en",
      stars: 5,
      title: "Saturdays stopped leaking",
      body: "We used to quote ‘it depends’ in DMs and then give away a 12-hour Saturday. Photographer Client Studio treats the date as inventory before we answer.",
      display_name: "Rachel Nguyen",
      city_country: "Toronto · Wedding studio",
      source: "customer",
    },
    {
      product_sku: "DW-SYS-010",
      locale: "en",
      stars: 5,
      title: "Gallery after the balance",
      body: "Retainer gate plus paid-in-full gallery closed the leak. Commercial clients stop getting the preview link before the invoice clears.",
      display_name: "Oliver Grant",
      city_country: "Sydney · Commercial photo",
      source: "customer",
    },
    {
      product_sku: "DW-SYS-010",
      locale: "fr",
      stars: 5,
      title: "La galerie après le solde",
      body: "L’acompte et la galerie soldée sont devenus la règle. Plus de lien preview avant le paiement.",
      display_name: "Camille Dupont",
      city_country: "Paris · Studio mariage",
      source: "customer",
    },
    {
      product_sku: "DW-SYS-010",
      locale: "es",
      stars: 5,
      title: "Revisiones con precio",
      body: "Dos rondas en el preview, extras con tarifa. El escritorio corta la fuga de ‘hazlo más mágico’.",
      display_name: "Lucia Herrera",
      city_country: "Madrid · Retrato",
      source: "customer",
    },
    {
      product_sku: "DW-EBK-001",
      locale: "en",
      stars: 5,
      title: "Paperwork before the OBD",
      body: "At $19.99 this is the clearest authorized apprenticeship I have bought. ID and registration first — then Add Key. No YouTube dare energy.",
      display_name: "Ryan Keller",
      city_country: "Phoenix · Mobile auto-key",
      source: "customer",
    },
    {
      product_sku: "DW-EBK-001",
      locale: "en",
      stars: 5,
      title: "Power first, then write",
      body: "A ‘dead immobilizer’ was a dying support battery. The manual’s callouts saved a module I was about to brick.",
      display_name: "Chris Delgado",
      city_country: "Houston · Shop bay",
      source: "customer",
    },
    {
      product_sku: "DW-EBK-001",
      locale: "fr",
      stars: 5,
      title: "Référer le luxe",
      body: "Les limites de plateforme sont un chapitre, pas une note. On marche quand on ne tient pas le cluster.",
      display_name: "Julien Moreau",
      city_country: "Lyon · Serrurerie mobile",
      source: "customer",
    },
    {
      product_sku: "DW-EBK-001",
      locale: "es",
      stars: 5,
      title: "Add Key primero",
      body: "Cotizábamos All Keys Lost desde un clip. El libro obliga a verificar el dueño y el mando que ya existe.",
      display_name: "Diego Romero",
      city_country: "Valencia · Cerrajería",
      source: "customer",
    },
    {
      product_sku: "DW-SYS-011",
      locale: "en",
      stars: 5,
      title: "Finally a CRM I own",
      body: "Professional CRM replaced Notes, chat tasks, and a folder of invoices. Customer Relationship Management without a monthly login.",
      display_name: "Priya Sharma",
      city_country: "Singapore · Freelance ops",
      source: "customer",
    },
    {
      product_sku: "DW-SYS-011",
      locale: "en",
      stars: 5,
      title: "Dashboard looked alive night one",
      body: "Sample clients made the desk feel real. I swapped them for my book the same evening. CSV for the accountant.",
      display_name: "Noah Pedersen",
      city_country: "Copenhagen · Agency start",
      source: "customer",
    },
    {
      product_sku: "DW-SYS-011",
      locale: "en",
      stars: 5,
      title: "Phone and desktop, same desk",
      body: "Installed to the home screen. Bottom tabs on phone, full windows on laptop. Same private Customer Relationship Management data.",
      display_name: "Hannah Cole",
      city_country: "Chicago · Solo consultant",
      source: "customer",
    },
    {
      product_sku: "DW-SYS-011",
      locale: "fr",
      stars: 5,
      title: "Un vrai CRM hors ligne",
      body: "Clients, tâches, factures, calendrier — un seul HTML. Plus de SaaS mensuel pour une petite équipe.",
      display_name: "Thomas Bernard",
      city_country: "Bruxelles · Studio",
      source: "customer",
    },
    {
      product_sku: "DW-SYS-011",
      locale: "es",
      stars: 5,
      title: "CRM sin suscripción",
      body: "Professional CRM es Customer Relationship Management en un archivo. Exporto CSV y listo.",
      display_name: "Ana Ruiz",
      city_country: "Mexico City · Freelance",
      source: "customer",
    },
    {
      product_sku: "DW-SYS-012",
      locale: "en",
      stars: 5,
      title: "Quotes left WhatsApp",
      body: "I stopped typing totals in chat. Quote, convert to invoice, print PDF, mark paid. Money desk finally exists.",
      display_name: "Liam Foster",
      city_country: "Dublin · Designer",
      source: "customer",
    },
    {
      product_sku: "DW-SYS-012",
      locale: "en",
      stars: 5,
      title: "Overdue is a number now",
      body: "Dashboard shows unpaid and overdue. I chase with facts, not a vague feeling someone still owes me.",
      display_name: "Grace Kim",
      city_country: "Seoul · Content studio",
      source: "customer",
    },
    {
      product_sku: "DW-SYS-012",
      locale: "fr",
      stars: 5,
      title: "Devis puis facture",
      body: "Conversion en un clic, PDF pour le client, marquer payé. Simple et sérieux.",
      display_name: "Isabelle Petit",
      city_country: "Nice · Coach",
      source: "customer",
    },
    {
      product_sku: "DW-SYS-012",
      locale: "es",
      stars: 5,
      title: "PDF listo en un clic",
      body: "Marca, impuesto y nota de pago en cada página. Cobro más rápido desde que dejé Word.",
      display_name: "Carlos Mendes",
      city_country: "Lisbon · Consultant",
      source: "customer",
    },
  ],
  products: [
    {
      sku: "DW-SYS-010",
      slug: "photographer-os",
      type: "system",
      serial: "DW-SYS-010",
      collection: "creator-lab",
      name: L("Photographer Client Studio", "استوديو عملاء المصور", "Studio client photographe", "Estudio de clientes para fotógrafos"),
      headline: L("A Saturday is inventory. Stop leaking it.", "السبت مخزون. وقف تسرّبه.", "Un samedi est un stock. Arrêtez de le brader.", "Un sábado es inventario. Deja de regalarlo."),
      sub: L(
        "The 90-minute desk for wedding and commercial photographers who leak jobs in DMs and hours in ‘unlimited’ galleries.",
        "مكتب 90 دقيقة لمصوري الأعراس والتجاري اللي يضيّعون الشغل في الخاص والساعات في معارض «بدون حد».",
        "Le bureau 90 minutes pour photographes mariage et commercial qui perdent les jobs en DM et les heures en galeries « illimitées ».",
        "El escritorio de 90 minutos para fotógrafos de boda y comercial que pierden trabajos en DMs y horas en galerías «ilimitadas».",
      ),
      description: L(
        "This is the operating system of a photography studio that books, shoots, delivers, and collects.\n\nGeneric freelancer CRMs fail photographers because a wedding is not a logo project. Dates are inventory. Saturdays are finite. Usage rights are where commercial profit lives.\n\nInstall in order: true-hourly math → rate card → board → 15-minute inquiry → retainer gate → 15-minute formals → revision cap → paid-in-full gallery → invoices. Sheets and Notion are both first-class. The local calculator shows a bad package before you send it.",
        "هذا نظام تشغيل استوديو تصوير يحجز، يصور، يسلّم، ويحصّل.\n\nقوالب الفريلانسر العامة تفشل المصور لأن العرس مو مشروع لوقو. التواريخ مخزون. السبت محدود. حقوق الاستخدام هي ربح التجاري.\n\nركّب بالترتيب: الساعة الحقيقية → التسعيرة → اللوحة → رد 15 دقيقة → بوابة العربون → الفورمالز → حد التعديل → المعرض بعد السداد → الفواتير. الشيتس والنوشن الاثنين أساس.",
        "C’est l’OS d’un studio qui réserve, shoot, livre et encaisse.\n\nUn CRM freelance générique rate le photographe : un mariage n’est pas un logo. Les samedis sont un stock. Les droits d’usage font le profit commercial.\n\nInstaller dans l’ordre : tarif horaire réel → grille → board → réponse 15 min → acompte → formelles → plafond de retouches → galerie soldée → factures.",
        "Es el sistema de un estudio que reserva, dispara, entrega y cobra.\n\nUn CRM genérico de freelance falla: una boda no es un logo. Los sábados son inventario. Los derechos de uso son el margen comercial.\n\nInstala en orden: tarifa real → lista → tablero → respuesta 15 min → anticipo → formales → tope de revisiones → galería pagada → facturas.",
      ),
      contents: L(
        "START-HERE (90 min)\nStudio math + Monday rhythm + Notion schema\n15-minute inquiry, qualifier, objections\nPackages, usage rights, rate CSV + local calculator\nBooking SOP, questionnaires, 15-min formals, retainer gate\nWedding-day production, shot lists, second shooter\nGallery, revision cap, raws, prints\nInvoices, chase scripts, money log\nSheets boards + welcome packet + emails",
        "ابدأ من هنا (90 د)\nحساب الاستوديو + إيقاع الاثنين + مخطط نوشن\nرد 15 دقيقة، تصفية، اعتراضات\nباقات، استخدام، CSV تسعيرة + حاسبة\nحجز، استبيانات، فورمالز، عربون\nإنتاج يوم العرس، لقطات، مصور ثاني\nمعرض، حد تعديل، ملفات خام، طباعة\nفواتير، ملاحقة، سجل مال\nلوحات شيتس + باقة ترحيب + إيميلات",
        "START-HERE (90 min)\nMath studio + lundi + schéma Notion\nInquiry 15 min, filtre, objections\nOffres, usage, CSV tarifs + calculateur\nBooking, questionnaires, formelles, acompte\nJour J, listes de plans, second shooter\nGalerie, plafond retouches, RAW, tirages\nFactures, relances, journal\nBoards Sheets + welcome + e-mails",
        "START-HERE (90 min)\nCuentas del estudio + lunes + esquema Notion\nInquiry 15 min, filtro, objeciones\nPaquetes, uso, CSV de tarifas + calculadora\nReserva, cuestionarios, formales, anticipo\nDía de boda, listas, segundo disparador\nGalería, tope de revisiones, RAW, copias\nFacturas, cobro, registro\nTableros Sheets + bienvenida + emails",
      ),
      faq: [
        {
          en: { q: "Is this a Notion template I duplicate in one click?", a: "It is a studio operating system: Notion schema, Google Sheets CSVs, a local calculator, SOPs, questionnaires, emails, and a welcome packet. START-HERE is 90 minutes. Not an empty aesthetic dashboard." },
          ar: { q: "هذا قالب نوشن ينسخ بضغطة؟", a: "نظام تشغيل للاستوديو: نوشن، جداول، حاسبة، إجراءات، استبيانات، إيميلات، باقة ترحيب. 90 دقيقة. مو لوحة شكل." },
          fr: { q: "C’est un template Notion en un clic ?", a: "Un OS de studio : Notion, CSV, calculateur, SOP, questionnaires, e-mails. 90 minutes. Pas un dashboard vide." },
          es: { q: "¿Es una plantilla de Notion de un clic?", a: "Un sistema de estudio: Notion, CSV, calculadora, SOPs, emails. 90 minutos. No un tablero vacío." },
        },
        {
          en: { q: "Do I have to use Notion?", a: "No. Sheets and Notion are both first-class. Copy the CSVs into Google Sheets, or build the board from the Notion schema. Do not rebuild the databases before you set prices." },
          ar: { q: "لازم نوشن؟", a: "لا. الشيتس والنوشن الاثنين أساس. انسخ الـCSV أو ابنِ اللوحة من مخطط نوشن. لا تبني قواعد فاضية قبل الأسعار." },
          fr: { q: "Je dois utiliser Notion ?", a: "Non. Sheets et Notion sont au même niveau. Copiez les CSV, ou construisez le board. Ne reconstruisez pas les bases avant les prix." },
          es: { q: "¿Tengo que usar Notion?", a: "No. Sheets y Notion van a la par. Copia los CSV o arma el tablero. No reconstruyas bases vacías antes de los precios." },
        },
        {
          en: { q: "Is this a lawyer-drafted contract or a lighting course?", a: "Neither. You get operating checklists, a retainer gate, and a service-agreement skeleton. Counsel in your country reviews the actual agreement. There is no posing or flash lesson in the zip." },
          ar: { q: "هذا عقد محامي أو دورة إضاءة؟", a: "ولا هذا ولا هذا. قوائم تشغيل، بوابة عربون، هيكل اتفاقية. المحامي عندك يراجع العقد. ما فيه درس بوز أو فلاش." },
          fr: { q: "C’est un contrat d’avocat ou un cours lumière ?", a: "Ni l’un ni l’autre. Checklists, acompte, squelette d’accord. Votre conseil relit le contrat. Pas de cours de pose." },
          es: { q: "¿Es un contrato de abogado o un curso de luz?", a: "Ninguno. Listas de operación, anticipo, esqueleto de acuerdo. Tu abogado revisa el contrato. No hay clase de pose." },
        },
        {
          en: { q: "What is the difference from the Etsy pack?", a: "Etsy is the $49 cousin: inquiry desk, Notion/Sheets, HTML OS. This site zip is the full studio vault — serial DW-SYS-010, duo seats, production and money SOPs, calculator, welcome packet. We do not dump the vault on Etsy." },
          ar: { q: "وش الفرق عن باقة إتسي؟", a: "إتسي ابن عم بـ49$: مكتب استفسار، نوشن/شيتس، نظام HTML. هنا الخزنة كاملة — رقم DW-SYS-010، مقعدين، إنتاج ومال، حاسبة، باقة ترحيب. ما نرمي الخزنة على إتسي." },
          fr: { q: "Quelle différence avec Etsy ?", a: "Etsy est le cousin à 49 $ : inquiry, Notion/Sheets, OS HTML. Ici, le vault complet — serial DW-SYS-010, duo, SOP production et argent. On ne brade pas le vault sur Etsy." },
          es: { q: "¿Qué cambia frente a Etsy?", a: "Etsy es el primo a 49 $: inquiry, Notion/Sheets, OS HTML. Aquí está el vault completo — serial DW-SYS-010, dúo, SOPs de producción y dinero. No tiramos el vault en Etsy." },
        },
        {
          en: { q: "How many seats? Can I resell it?", a: "One studio is $35. Two seats (you + second shooter or partner) is $55. Personal install only. No redistribution, no Etsy dump of this zip." },
          ar: { q: "كم مقعد؟ أقدر أبيعه؟", a: "استوديو واحد 35$. مقعدين (أنت + مصور ثاني أو شريك) 55$. تركيب شخصي. بدون إعادة نشر، وبدون رمي هذا الزيب على إتسي." },
          fr: { q: "Combien de sièges ? Je peux le revendre ?", a: "Un studio = 35 $. Deux sièges = 55 $. Install perso. Pas de redistribution, pas de dump Etsy de ce zip." },
          es: { q: "¿Cuántos asientos? ¿Puedo revenderlo?", a: "Un estudio = 35 $. Dos asientos = 55 $. Instalación personal. Sin reventa ni dump en Etsy de este zip." },
        },
        {
          en: { q: "How do I get the files? Refund?", a: "After name and email, the thank-you page has the zip. We also email that inbox. 7-day replacement if the zip is corrupt or will not open. We never sold a certificate." },
          ar: { q: "كيف يوصلني الملف؟ استرجاع؟", a: "بعد الاسم والإيميل، صفحة الشكر فيها الزيب. ونراسل نفس الإيميل. استبدال 7 أيام إذا الملف خربان أو ما ينفتح. ما بعنا شهادة." },
          fr: { q: "Comment je reçois les fichiers ? Remboursement ?", a: "Après nom et e-mail, la page merci a le zip. 7 jours si le zip est corrompu. On n’a jamais vendu un certificat." },
          es: { q: "¿Cómo recibo los archivos? ¿Reembolso?", a: "Tras nombre y email, la página de gracias tiene el zip. 7 días si el zip está mal o no abre. Nunca vendimos un certificado." },
        },
      ],
      images: ["/images/products/photographer-os/01.png", "/images/products/photographer-os/02.png", "/images/products/photographer-os/03.png", "/images/products/photographer-os/04.png"],
      price_cents: 3500,
      duo_price_cents: 5500,
      cross_sell: [],
      license_pool: 250,
      licenses_issued: 0,
      drop_label: "Drop 01 — 2026",
    },
    {
      sku: "DW-EBK-001",
      slug: "key-fob-programming-mastery",
      type: "system",
      serial: "DW-EBK-001",
      collection: "trades-lab",
      name: L("Key Fob Programming Mastery", "إتقان برمجة ريموت السيارة", "Maîtrise de la programmation de télécommandes", "Dominio de la programación de mandos"),
      headline: L("Program the spare. Prove the owner. Leave the shortcuts alone.", "برمج الاحتياطي. ثبّت المالك. اترك الاختصارات.", "Programmez la copie. Prouvez le propriétaire. Laissez les raccourcis.", "Programa el recambio. Prueba al dueño. Deja los atajos."),
      sub: L(
        "Complete visual apprenticeship for authorized key-fob and immobilizer work: verify the owner, quote the job, prep the remote, run the procedure, test the finish, refer what you cannot support.",
        "تدريب بصري كامل لبرمجة الريموت والإيموبيلايزر المصرّح: تحقق من المالك، سعّر الشغل، حضّر الريموت، نفّذ الإجراء، اختبر النهاية، وأحل ما لا تدعمه.",
        "Apprentissage visuel complet pour télécommandes et antivol autorisés : vérifier le propriétaire, chiffrer, préparer, programmer, tester, transférer ce que vous ne tenez pas.",
        "Aprendizaje visual completo para mando e inmovilizador autorizado: verifica al dueño, cotiza, prepara, programa, prueba, deriva lo que no puedas.",
      ),
      description: L(
        "This is a trade apprenticeship in PDF form — authorized automotive key-fob work for verified vehicle owners only.\n\nYou do not become competent by skimming a YouTube dare. You verify the owner, quote Add Key vs All Keys Lost, prepare the remote, follow the procedure, test the finish, and refer what you cannot support.\n\nWeak vehicle batteries brick more jobs than bad technicians. Luxury platforms get a referral, not a miracle. This product does not teach theft, skipped paperwork, stolen-vehicle starts, undocumented immobilizer bypass, EEPROM attacks, or dealer-login abuse.",
        "هذا تدريب مهني بصيغة PDF — شغل ريموت مصرّح لمالك السيارة المتحقق منه فقط.\n\nما تصير كفء بتقليد يوتيوب. تتحقق من المالك، تسعّر إضافة مفتاح مقابل كل المفاتيح ضائعة، تحضّر الريموت، تتبع الإجراء، تختبر، وتحيل اللي ما تدعمه.\n\nالبطارية الضعيفة تخرب شغل أكثر من الفني الغلط. المنصات الفخمة تُحال، مو معجزة. هذا المنتج ما يعلّم سرقة ولا تجاوز إيموبيلايزر ولا هجوم EEPROM ولا إساءة دخول الوكيل.",
        "Un apprentissage de métier en PDF — travail autorisé sur télécommande pour le propriétaire vérifié seulement.\n\nOn ne devient pas compétent en copiant YouTube. Vérifier le propriétaire, chiffrer Add Key vs All Keys Lost, préparer, suivre, tester, transférer.\n\nUne batterie faible brique plus de jobs qu’un mauvais tech. Le luxe se transmet, il ne se « miracle » pas. Pas de vol, pas de bypass, pas d’attaque EEPROM, pas d’abus de login concessionnaire.",
        "Un aprendizaje de oficio en PDF — trabajo autorizado de mando para el dueño verificado.\n\nNo te haces competente imitando YouTube. Verifica al dueño, cotiza Add Key vs All Keys Lost, prepara, sigue el procedimiento, prueba, deriva.\n\nUna batería débil rompe más trabajos que un mal técnico. El lujo se deriva, no se inventa. No enseña robo, bypass, ataques EEPROM ni abuso de login de concesionario.",
      ),
      contents: L(
        "START-HERE (study path, ethics, licence)\n22-chapter illustrated field manual (PDF)\nLaw, ethics, paperwork — ID + registration before OBD\nFob anatomy, immobilizers, RKE vs smart vs blade+chip\nMachines, kits, consumables (with prices)\nProcedure A — Add a spare\nProcedure B — Lost remote, car present\nProcedure C — All Keys Lost\nCutting, programming discipline, testing, fault-finding\nLuxury limits & referral · pricing the customer\n90-day competence calendar · glossary · packing list",
        "ابدأ من هنا (دراسة، أخلاق، رخصة)\nدليل ميداني مصوّر 22 فصلاً (PDF)\nقانون وأوراق — هوية + استمارة قبل أي كتابة\nتشريح الريموت، إيموبيلايزر، أنواع المفاتيح\nمكائن وعدد وأسعار\nإجراء أ — إضافة احتياطي\nإجراء ب — ريموت ضائع والسيارة موجودة\nإجراء ج — كل المفاتيح ضائعة\nقص، انضباط برمجة، اختبار، أعطال\nحدود الفخم والإحالة · تسعير العميل\nمسار 90 يوم · قاموس · قائمة تعبئة",
        "START-HERE (étude, éthique, licence)\nManuel illustré 22 chapitres (PDF)\nDroit et papiers — pièce + carte grise avant l’OBD\nAnatomie, antivol, types de clés\nMachines, kits, consommables (prix)\nProcédure A — ajouter une copie\nProcédure B — télécommande perdue, véhicule présent\nProcédure C — All Keys Lost\nTaille, discipline, tests, pannes\nLimites luxe & transfert · prix client\nCalendrier 90 jours · glossaire · packing",
        "START-HERE (estudio, ética, licencia)\nManual ilustrado 22 capítulos (PDF)\nLey y papeles — ID + registro antes del OBD\nAnatomía, inmovilizador, tipos de mando\nMáquinas, kits, consumibles (precios)\nProcedimiento A — añadir recambio\nProcedimiento B — mando perdido, coche presente\nProcedimiento C — All Keys Lost\nCorte, disciplina, prueba, fallos\nLímites de lujo y derivación · precio al cliente\nCalendario 90 días · glosario · packing",
      ),
      faq: [
        {
          en: { q: "Is this a theft, bypass, or stolen-vehicle guide?", a: "No. Authorized work for the verified owner (or documented authorized agent) only. Photo ID + registration/title. Log it. Walk away from a bad story. No skipped paperwork, no undocumented immobilizer bypass, no EEPROM attacks, no dealer-login abuse." },
          ar: { q: "هذا دليل سرقة أو تجاوز إيموبيلايزر؟", a: "لا. شغل مصرّح لمالك السيارة المتحقق منه فقط. هوية + استمارة. سجّل. اطلع إذا القصة غلط. ما فيه تجاوز، ولا هجوم EEPROM، ولا إساءة دخول الوكيل." },
          fr: { q: "C’est un guide vol / bypass ?", a: "Non. Travail autorisé pour le propriétaire vérifié seulement. Pièce + carte grise. Journal. On s’arrête si l’histoire cloche. Pas de bypass, pas d’attaque EEPROM, pas d’abus de login concessionnaire." },
          es: { q: "¿Es una guía de robo o bypass?", a: "No. Trabajo autorizado para el dueño verificado. ID + registro. Bitácora. Si la historia no cuadra, el trabajo termina. Sin bypass, sin ataques EEPROM, sin abuso de login de concesionario." },
        },
        {
          en: { q: "Will it program every car? Do I get a dealer login?", a: "No. The book teaches you to read the car, run supported procedures, and refer luxury platforms you cannot support. There is no dealer-login dump and no ‘works on every VIN’ claim." },
          ar: { q: "يبرمج كل سيارة؟ فيه دخول وكيل؟", a: "لا. تعلّمك تقرأ السيارة، تنفّذ الإجراءات المدعومة، وتحيل المنصات الفخمة اللي ما تدعمها. ما فيه سحب دخول وكيل ولا وعد «على كل فيش»." },
          fr: { q: "Ça programme toutes les voitures ? Un login concessionnaire ?", a: "Non. Lire le véhicule, suivre les procédures supportées, transférer le luxe que vous ne tenez pas. Pas de dump de login, pas de « tous les VIN »." },
          es: { q: "¿Programa todos los coches? ¿Login de concesionario?", a: "No. Leer el coche, seguir procedimientos soportados, derivar lujo que no puedes. Sin dump de login ni «sirve en todo VIN»." },
        },
        {
          en: { q: "Do I need a specific programmer before I buy?", a: "You need a legally owned practice vehicle, ownership paperwork, and eventually a real kit. Chapter 8 covers machines and kits with prices so you buy once. The PDF is not a substitute for a tablet or a cutter." },
          ar: { q: "لازم جهاز معيّن قبل الشراء؟", a: "تحتاج سيارة تدريب تملكها قانونياً، أوراق المالك، وبعدين عدة حقيقية. الفصل 8 فيه المكائن والأسعار عشان تشتري مرة. الـPDF مو بديل للجهاز." },
          fr: { q: "Il me faut une machine précise avant d’acheter ?", a: "Véhicule d’entraînement en votre nom, papiers, puis un vrai kit. Le ch. 8 liste machines et prix. Le PDF ne remplace pas la tablette." },
          es: { q: "¿Necesito una máquina concreta antes de comprar?", a: "Un coche de práctica de tu propiedad, papeles, y luego un kit real. El cap. 8 lista máquinas y precios. El PDF no sustituye la tablet." },
        },
        {
          en: { q: "How many seats? Can I resell the PDF?", a: "One technician is $19.99. Two shop seats is $29.99. Personal use. No redistribution, no marketplace dump of this PDF." },
          ar: { q: "كم مقعد؟ أقدر أبيع الـPDF؟", a: "فني واحد 19.99$. مقعدين للورشة 29.99$. استخدام شخصي. بدون إعادة نشر وبدون رمي الـPDF على الأسواق." },
          fr: { q: "Combien de sièges ? Je peux revendre le PDF ?", a: "Un tech = 19,99 $. Deux sièges atelier = 29,99 $. Usage perso. Pas de redistribution, pas de dump marketplace." },
          es: { q: "¿Cuántos asientos? ¿Puedo revender el PDF?", a: "Un técnico = 19,99 $. Dos asientos de taller = 29,99 $. Uso personal. Sin reventa ni dump en marketplaces." },
        },
        {
          en: { q: "How do I get the files? Refund?", a: "After name and email, the thank-you page has the zip. We also email that inbox. 7-day replacement if the zip is corrupt or will not open. This is not a certificate and not legal advice." },
          ar: { q: "كيف يوصلني الملف؟ استرجاع؟", a: "بعد الاسم والإيميل، صفحة الشكر فيها الزيب. ونراسل نفس الإيميل. استبدال 7 أيام إذا الملف خربان. مو شهادة ومو استشارة قانونية." },
          fr: { q: "Comment je reçois les fichiers ? Remboursement ?", a: "Après nom et e-mail, la page merci a le zip. 7 jours si le zip est corrompu. Pas un certificat, pas un avis juridique." },
          es: { q: "¿Cómo recibo los archivos? ¿Reembolso?", a: "Tras nombre y email, la página de gracias tiene el zip. 7 días si el zip no abre. No es certificado ni consejo legal." },
        },
        {
          en: { q: "What is in the zip besides the ebook?", a: "START-HERE (how to study, ethics, licence) and Key-Fob-Programming-Mastery.pdf. The 22 chapters, checklists, and packing list live inside the book. We do not ship Car-Key-Programming-Pro as this SKU." },
          ar: { q: "وش داخل الزيب غير الكتاب؟", a: "ابدأ من هنا (دراسة، أخلاق، رخصة) وملف Key-Fob-Programming-Mastery.pdf. الاثنان وعشرون فصلاً والقوائم داخل الكتاب. ما نبيع Car-Key-Programming-Pro كهذا المنتج." },
          fr: { q: "Quoi d’autre dans le zip ?", a: "START-HERE (étude, éthique, licence) et le PDF. Les 22 chapitres sont dans le livre. On ne vend pas Car-Key-Programming-Pro sous ce SKU." },
          es: { q: "¿Qué más hay en el zip?", a: "START-HERE (estudio, ética, licencia) y el PDF. Los 22 capítulos van en el libro. No vendemos Car-Key-Programming-Pro como este SKU." },
        },
      ],
      images: [
        "/images/products/key-fob-programming-mastery/01.png",
        "/images/products/key-fob-programming-mastery/02.png",
        "/images/products/key-fob-programming-mastery/03.png",
        "/images/products/key-fob-programming-mastery/04.png",
        "/images/products/key-fob-programming-mastery/05.png",
        "/images/products/key-fob-programming-mastery/06.png",
        "/images/products/key-fob-programming-mastery/07.png",
        "/images/products/key-fob-programming-mastery/08.png",
        "/images/products/key-fob-programming-mastery/09.png",
        "/images/products/key-fob-programming-mastery/10.png",
      ],
      price_cents: 1999,
      duo_price_cents: 2999,
      cross_sell: [],
      license_pool: 250,
      licenses_issued: 0,
      drop_label: "Drop 01 — 2026",
    },
    {
      sku: "DW-SYS-011",
      slug: "client-tracker",
      type: "system",
      serial: "DW-SYS-011",
      collection: "creator-lab",
      name: L("Digi World Professional CRM", "نظام CRM الاحترافي — ديجي وورلد", "CRM Professionnel Digi World", "CRM Profesional Digi World"),
      headline: L(
        "Customer Relationship Management — one offline desk.",
        "إدارة علاقات العملاء — مكتب واحد أوفلاين.",
        "Customer Relationship Management — un bureau hors ligne.",
        "Customer Relationship Management — un escritorio offline.",
      ),
      sub: L(
        "Offline HTML CRM: clients, communication log, tasks, calendar, invoices, budget, overview, dashboard — CSV export. No Google account.",
        "CRM HTML بدون إنترنت: عملاء، سجل تواصل، مهام، تقويم، فواتير، ميزانية، نظرة، لوحة — تصدير CSV. بدون حساب قوقل.",
        "CRM HTML hors ligne : clients, journal, tâches, calendrier, factures, budget, vue, dashboard — export CSV. Pas de compte Google.",
        "CRM HTML offline: clientes, log, tareas, calendario, facturas, presupuesto, vista, panel — export CSV. Sin cuenta Google.",
      ),
      description: L(
        "A freelancer’s desk that actually keeps the follow-up alive — on computer or phone.\n\nInstall as a phone app (Add to Home Screen / Install app): full-screen with bottom tabs, a + button, and offline support. Same private desk on desktop: Setup, Client Database, Communication Log, Task Tracker, Smart Calendar, Client Overview, Dashboard, Invoices, Budget, Files.\n\nCharts update when you add a row. Export CSV for this window or the whole desk. Import clients from CSV on Setup.\n\nNo Google Sheets. No Notion login. Data stays on this device.",
        "مكتب فريلانسر يحافظ على المتابعة — على الكمبيوتر أو الجوال.\n\nثبّته كتطبيق جوال (إضافة إلى الشاشة الرئيسية): ملء الشاشة مع تبويبات وزر + وأوفلاين. نفس المكتب على الكمبيوتر.\n\nصدّر CSV. استورد عملاء. بدون قوقل شيتس. البيانات على جهازك.",
        "Un bureau freelance qui garde les relances vivantes — ordinateur ou téléphone.\n\nInstallez l’app (Ajouter à l’écran d’accueil) : plein écran, onglets, bouton +, offline. Même bureau sur desktop.\n\nExport CSV. Import clients. Pas de Google Sheets. Les données restent ici.",
        "Un escritorio freelance que mantiene el seguimiento — PC o móvil.\n\nInstálalo como app (Añadir a inicio): pantalla completa, pestañas, botón +, offline. El mismo escritorio en PC.\n\nExport CSV. Importa clientes. Sin Google Sheets. Los datos se quedan aquí.",
      ),
      contents: L(
        "START-HERE\nClient-Tracker.html (phone PWA + desktop)\nmanifest + service worker + icons\nBottom tabs / FAB on phone\nSetup with editable dropdowns\nClient Database + charts\nInvoices + Budget + Files\nCommunication Log\nTask Tracker (KPIs, overdue, filters)\nSmart Calendar\nClient Overview (360°)\nDashboard\nExport / import CSV\nSample desk included",
        "ابدأ من هنا\nClient-Tracker.html (PWA جوال + سطح مكتب)\nmanifest + service worker + أيقونات\nتبويبات وزر + للجوال\nإعداد القوائم\nقاعدة عملاء + رسوم\nفواتير + ميزانية + ملفات\nسجل تواصل\nمهام\nتقويم ذكي\nنظرة عميل\nلوحة تحكم\nتصدير/استيراد CSV\nبيانات تجريبية",
        "START-HERE\nClient-Tracker.html (PWA téléphone + bureau)\nmanifest + service worker + icônes\nOnglets / FAB téléphone\nSetup listes\nBase clients + graphiques\nFactures + budget + fichiers\nJournal\nTâches\nCalendrier\nVue client\nDashboard\nExport / import CSV\nDonnées exemple",
        "START-HERE\nClient-Tracker.html (PWA móvil + escritorio)\nmanifest + service worker + iconos\nPestañas / FAB móvil\nSetup listas\nBase de clientes + gráficos\nFacturas + presupuesto + archivos\nLog de comunicación\nTareas\nCalendario\nVista de cliente\nPanel\nExport / import CSV\nDatos de ejemplo",
      ),
      faq: [
        {
          en: { q: "Do I need Google Sheets or Notion?", a: "No. Double-click Client-Tracker.html. It runs in your browser. Data stays on this computer in localStorage." },
          ar: { q: "لازم قوقل شيتس أو نوشن؟", a: "لا. افتح Client-Tracker.html. يشتغل بالمتصفح. البيانات تبقى على جهازك." },
          fr: { q: "Il me faut Google Sheets ou Notion ?", a: "Non. Double-cliquez Client-Tracker.html. Ça tourne dans le navigateur. Les données restent sur cet ordinateur." },
          es: { q: "¿Necesito Google Sheets o Notion?", a: "No. Abre Client-Tracker.html. Corre en el navegador. Los datos se quedan en este ordenador." },
        },
        {
          en: { q: "What are the seven windows?", a: "Setup, Client Database, Communication Log, Task Tracker, Smart Calendar, Client Overview, and Dashboard — one shared data store." },
          ar: { q: "وش السبع نوافذ؟", a: "الإعداد، قاعدة العملاء، سجل التواصل، متتبع المهام، التقويم، نظرة العميل، ولوحة التحكم — مخزن بيانات واحد." },
          fr: { q: "Quelles sont les sept fenêtres ?", a: "Setup, base clients, journal de communication, tâches, calendrier, vue client, et tableau de bord — une seule base." },
          es: { q: "¿Cuáles son las siete ventanas?", a: "Setup, base de clientes, log de comunicación, tareas, calendario, vista de cliente y panel — un solo almacén." },
        },
        {
          en: { q: "Can I export to CSV / Excel?", a: "Yes. Export CSV exports this window or all data (clients, communications, tasks, setup) with Excel-safe UTF-8 BOM. Setup also imports a clients CSV." },
          ar: { q: "أقدر أصدّر CSV / إكسل؟", a: "نعم. تصدير CSV لهذه النافذة أو لكل البيانات. الإعداد يستورد CSV عملاء أيضاً." },
          fr: { q: "Export CSV / Excel ?", a: "Oui. Export CSV pour la fenêtre ou toutes les données. Setup importe aussi un CSV clients." },
          es: { q: "¿Puedo exportar a CSV / Excel?", a: "Sí. Export CSV de esta ventana o de todos los datos. Setup también importa un CSV de clientes." },
        },
        {
          en: { q: "Can I use it on my phone?", a: "Yes. Serve or host the folder, open Client-Tracker.html, then Add to Home Screen (iPhone) or Install app (Android). You get bottom tabs, a + button, and offline use. Same private data on the device." },
          ar: { q: "أقدر أستخدمه على الجوال؟", a: "نعم. افتح Client-Tracker.html ثم أضفه للشاشة الرئيسية (آيفون) أو ثبّت التطبيق (أندرويد). تبويبات سفلية وزر + وأوفلاين. نفس البيانات الخاصة على الجهاز." },
          fr: { q: "Ça marche sur téléphone ?", a: "Oui. Ouvrez Client-Tracker.html puis Ajouter à l’écran d’accueil (iPhone) ou Installer l’app (Android). Onglets, bouton +, offline. Données privées sur l’appareil." },
          es: { q: "¿Funciona en el móvil?", a: "Sí. Abre Client-Tracker.html y Añadir a inicio (iPhone) o Instalar app (Android). Pestañas, botón +, offline. Datos privados en el dispositivo." },
        },
        {
          en: { q: "How many seats? Can I resell it?", a: "One studio is $39. Two seats is $59. Personal use. No redistribution, no marketplace dump of the HTML." },
          ar: { q: "كم مقعد؟ أقدر أبيعه؟", a: "استوديو واحد 39$. مقعدين 59$. استخدام شخصي. بدون إعادة نشر." },
          fr: { q: "Combien de sièges ? Je peux le revendre ?", a: "Un studio = 39 $. Deux sièges = 59 $. Usage perso. Pas de redistribution." },
          es: { q: "¿Cuántos asientos? ¿Puedo revenderlo?", a: "Un estudio = 39 $. Dos asientos = 59 $. Uso personal. Sin reventa." },
        },
        {
          en: { q: "How do I get the files? Refund?", a: "After name and email, the thank-you page has the zip. We also email that inbox. 7-day replacement if the zip will not open." },
          ar: { q: "كيف يوصلني الملف؟ استرجاع؟", a: "بعد الاسم والإيميل، صفحة الشكر فيها الزيب. استبدال 7 أيام إذا ما ينفتح." },
          fr: { q: "Comment je reçois les fichiers ?", a: "Après nom et e-mail, la page merci a le zip. 7 jours si le zip n’ouvre pas." },
          es: { q: "¿Cómo recibo los archivos?", a: "Tras nombre y email, la página de gracias tiene el zip. 7 días si no abre." },
        },
      ],
      images: [
        "/images/products/client-tracker/01.png",
        "/images/products/client-tracker/02.png",
        "/images/products/client-tracker/03.png",
        "/images/products/client-tracker/04.png",
        "/images/products/client-tracker/05.png",
        "/images/products/client-tracker/06.png",
        "/images/products/client-tracker/07.png",
        "/images/products/client-tracker/08.png",
        "/images/products/client-tracker/09.png",
        "/images/products/client-tracker/10.png",
        "/images/products/client-tracker/11.png",
      ],
      price_cents: 3900,
      duo_price_cents: 5900,
      cross_sell: [],
      license_pool: 250,
      licenses_issued: 0,
      drop_label: "Drop 01 — 2026",
    },
    {
      sku: "DW-SYS-012",
      slug: "invoice-desk",
      type: "system",
      serial: "DW-SYS-012",
      collection: "creator-lab",
      name: L("Quote & Invoice Desk", "مكتب العروض والفواتير", "Bureau devis & factures", "Escritorio de presupuestos y facturas"),
      headline: L(
        "Quote. Invoice. Get paid.",
        "عرض. فاتورة. حصّل.",
        "Devis. Facture. Encaissez.",
        "Presupuesto. Factura. Cobra.",
      ),
      sub: L(
        "Offline HTML money desk: quotes → invoices → paid. Print PDF. No QuickBooks login. Complements Professional CRM.",
        "مكتب مال HTML بدون إنترنت: عروض → فواتير → مدفوع. اطبع PDF. بدون كويك بوكس. يكمل الـCRM الاحترافي.",
        "Bureau argent HTML hors ligne : devis → factures → payé. PDF. Pas de QuickBooks. Complète le CRM Professionnel.",
        "Escritorio HTML offline: presupuestos → facturas → pagado. PDF. Sin QuickBooks. Complementa el CRM Profesional.",
      ),
      description: L(
        "Freelancers lose money in Word invoices and half-sent quotes.\n\nOne HTML desk: Setup your brand, tax, and payment note. Build quotes with line items. Convert an accepted quote into an invoice. Mark paid when the wire lands. Print or Save as PDF for the client.\n\nDashboard shows open quotes, unpaid, overdue, and outstanding. Data stays in localStorage — Digi World never sees your clients or amounts.\n\nPairs with Professional CRM for the relationship desk; this one is the money desk.",
        "الفريلانسر يضيّع فلوس في فواتير وورد وعروض نصف مرسلة.\n\nمكتب HTML واحد: إعداد العلامة والضريبة وملاحظة الدفع. ابنِ عروض ببنود. حوّل العرض المقبول لفاتورة. علّم مدفوع لما يوصل التحويل. اطبع أو احفظ PDF.\n\nاللوحة تعرض العروض المفتوحة وغير المدفوع والمتأخر والمستحق. البيانات محلية.\n\nيكمل الـCRM الاحترافي للعلاقات؛ هذا مكتب المال.",
        "Les freelances perdent de l’argent dans Word et des devis à moitié envoyés.\n\nUn bureau HTML : marque, taxe, note de paiement. Devis avec lignes. Convertissez un devis accepté en facture. Marquez payé. Imprimez ou PDF.\n\nLe dashboard montre devis ouverts, impayés, retard, encours. Données locales.\n\nComplète le CRM Professionnel ; ici, c’est l’argent.",
        "Los freelancers pierden dinero en facturas Word y presupuestos a medias.\n\nUn escritorio HTML: marca, impuesto, nota de pago. Presupuestos con líneas. Convierte uno aceptado en factura. Marca pagado. Imprime o PDF.\n\nEl panel muestra abiertos, impagos, vencidos y pendiente. Datos locales.\n\nComplementa el CRM Profesional; este es el escritorio del dinero.",
      ),
      contents: L(
        "START-HERE\nInvoice-Quote-Desk.html\nSetup (brand, tax, currency, payment note)\nDashboard (open / unpaid / overdue)\nQuotes with line items + status\nConvert quote → invoice\nInvoices + Mark paid\nPrint / Save as PDF\nSample desk included",
        "ابدأ من هنا\nInvoice-Quote-Desk.html\nإعداد (علامة، ضريبة، عملة، ملاحظة دفع)\nلوحة (مفتوح / غير مدفوع / متأخر)\nعروض ببنود + حالة\nتحويل عرض → فاتورة\nفواتير + تعليم مدفوع\nطباعة / حفظ PDF\nبيانات تجريبية",
        "START-HERE\nInvoice-Quote-Desk.html\nSetup (marque, taxe, devise, note)\nDashboard (ouverts / impayés / retard)\nDevis + lignes + statut\nConvertir devis → facture\nFactures + Marquer payé\nImprimer / PDF\nDonnées exemple",
        "START-HERE\nInvoice-Quote-Desk.html\nSetup (marca, impuesto, moneda, nota)\nPanel (abiertos / impagos / vencidos)\nPresupuestos + líneas + estado\nConvertir presupuesto → factura\nFacturas + Marcar pagado\nImprimir / PDF\nDatos de ejemplo",
      ),
      faq: [
        {
          en: { q: "Do I need QuickBooks, Wave, or Google Sheets?", a: "No. Double-click Invoice-Quote-Desk.html. Quotes and invoices stay in localStorage on this computer." },
          ar: { q: "لازم كويك بوكس أو ويف أو قوقل شيتس؟", a: "لا. افتح Invoice-Quote-Desk.html. العروض والفواتير تبقى على جهازك." },
          fr: { q: "Il me faut QuickBooks, Wave ou Google Sheets ?", a: "Non. Double-cliquez Invoice-Quote-Desk.html. Devis et factures restent en localStorage." },
          es: { q: "¿Necesito QuickBooks, Wave o Google Sheets?", a: "No. Abre Invoice-Quote-Desk.html. Presupuestos y facturas quedan en localStorage." },
        },
        {
          en: { q: "Can I turn a quote into an invoice?", a: "Yes. Accept the quote, then Convert — line items, client, and totals carry over. Edit before you send." },
          ar: { q: "أقدر أحّول العرض لفاتورة؟", a: "نعم. اقبل العرض ثم حوّل — البنود والعميل والمجاميع تنتقل. عدّل قبل الإرسال." },
          fr: { q: "Je peux convertir un devis en facture ?", a: "Oui. Acceptez le devis, puis Convertir — lignes, client et totaux suivent. Modifiez avant d’envoyer." },
          es: { q: "¿Puedo convertir un presupuesto en factura?", a: "Sí. Acepta el presupuesto y convierte — líneas, cliente y totales pasan. Edita antes de enviar." },
        },
        {
          en: { q: "How do I get a PDF?", a: "Open the document → Print → Save as PDF. Your business name, tax, and payment note print on the page." },
          ar: { q: "كيف أحصل على PDF؟", a: "افتح المستند → طباعة → حفظ كـ PDF. اسم النشاط والضريبة وملاحظة الدفع تطبع على الصفحة." },
          fr: { q: "Comment obtenir un PDF ?", a: "Ouvrez le document → Imprimer → Enregistrer en PDF. Nom, taxe et note de paiement s’impriment." },
          es: { q: "¿Cómo saco un PDF?", a: "Abre el documento → Imprimir → Guardar como PDF. Nombre, impuesto y nota de pago salen en la página." },
        },
        {
          en: { q: "How many seats? Can I resell it?", a: "One studio is $29. Two seats is $45. Personal use. No redistribution, no marketplace dump of the HTML." },
          ar: { q: "كم مقعد؟ أقدر أبيعه؟", a: "استوديو واحد 29$. مقعدين 45$. استخدام شخصي. بدون إعادة نشر." },
          fr: { q: "Combien de sièges ? Je peux le revendre ?", a: "Un studio = 29 $. Deux sièges = 45 $. Usage perso. Pas de redistribution." },
          es: { q: "¿Cuántos asientos? ¿Puedo revenderlo?", a: "Un estudio = 29 $. Dos asientos = 45 $. Uso personal. Sin reventa." },
        },
        {
          en: { q: "How do I get the files? Refund?", a: "After name and email, the thank-you page has the zip. We also email that inbox. 7-day replacement if the zip will not open." },
          ar: { q: "كيف يوصلني الملف؟ استرجاع؟", a: "بعد الاسم والإيميل، صفحة الشكر فيها الزيب. استبدال 7 أيام إذا ما ينفتح." },
          fr: { q: "Comment je reçois les fichiers ?", a: "Après nom et e-mail, la page merci a le zip. 7 jours si le zip n’ouvre pas." },
          es: { q: "¿Cómo recibo los archivos?", a: "Tras nombre y email, la página de gracias tiene el zip. 7 días si no abre." },
        },
      ],
      images: [
        "/images/products/invoice-desk/01.png",
        "/images/products/invoice-desk/02.png",
        "/images/products/invoice-desk/03.png",
        "/images/products/invoice-desk/04.png",
        "/images/products/invoice-desk/05.png",
        "/images/products/invoice-desk/06.png",
        "/images/products/invoice-desk/07.png",
      ],
      price_cents: 2900,
      duo_price_cents: 4500,
      cross_sell: ["DW-SYS-011"],
      license_pool: 250,
      licenses_issued: 0,
      drop_label: "Drop 01 — 2026",
    },
  ],
};
